// Generated by js_of_ocaml
//# buildInfo:effects=false, kind=exe, use-js-string=true, version=5.9.1
(function(a){typeof
globalThis!=="object"&&(this?b():(a.defineProperty(a.prototype,"_T_",{configurable:true,get:b}),_T_));function
b(){var
b=this||self;b.globalThis=b;delete
a.prototype._T_}}(Object));(function(c){"use strict";var
g9=typeof
module==="object"&&module.exports||c,c3="Sys_error",P=0x80,cz="ENOTEMPTY",bE="compare: functional value",_=" ",c2="EEXIST",G="0",bz=1255,aI=1000,bD="mkdir",cP="@[",by=" : flags Open_text and Open_binary are not compatible",bJ="e",dg="%u",cO="/static/",cy="Stack_overflow",bx=": Not a directory",bI="ENOENT",bN="node:fs",cN="%i",df="%ni",$=0xff,c1="Undefined_recursive_module",cM="Assert_failure",cL="0x",U=0x8000,cx=-48,c0=0x800,de=0x7ff0,cw=" : is a directory",cK=0xdfff,cY="@{",cZ="Division_by_zero",ao=".",dd="End_of_file",cJ=": closedir failed",aw=0x3f,dc="Out_of_memory",cI="Not_found",bH=" : file already exists",bM="Failure",aJ=": No such file or directory",aK=128,a1="Unix.Unix_error",db="^",cX=255,cW=256,bL="ENOTDIR",cV=100,Y="/",bw="index out of bounds",aY=252,cH="%Li",cG="Invalid_argument",aZ=254,ax="+",bv="%d",da=", characters ",cv=": file descriptor already closed",an="-",bu="EBADF",Z=0xffffff,cF=120,cE=1027,aH=1024,cT=-97,cU="Printexc.handle_uncaught_exception",c$="Pervasives.do_at_exit",cu=12520,bG=" : flags Open_rdonly and Open_wronly are not compatible",c_=65536,bK=0xf,cC=", ",cD=512,ct="Fatal error: exception %s\n",c8="Match_failure",c9="closedir",cA="%li",cB=1026,cs=250,bC="nan",f="",bA="Fatal error: exception ",bB="rmdir",cS="([^/]+)",bt="jsError",a="camlinternalFormat.ml",c7="infinity",cr=103,aX='"',T=0xffff,bF=127,c6="fd ",cq=0xdc00,cR="Sys_blocked_io",t=248,cQ="_",c5=0xe0,a0="_bigarr02",c4=0xf0;function
go(a,b,c){if(a[1]===b){a[1]=c;return 1}return 0}function
bO(a){return a[1]}function
bc(a,b,c){var
d=String.fromCharCode;if(b===0&&c<=4096&&c===a.length)return d.apply(null,a);var
e=f;for(;0<c;b+=aH,c-=aH)e+=d.apply(null,a.slice(b,b+Math.min(c,aH)));return e}function
a5(a){var
c=new
Uint8Array(a.l),e=a.c,d=e.length,b=0;for(;b<d;b++)c[b]=e.charCodeAt(b);for(d=a.l;b<d;b++)c[b]=0;a.c=c;a.t=4;return c}function
ai(a,b,c,d,e){if(e===0)return 0;if(d===0&&(e>=c.l||c.t===2&&e>=c.c.length)){c.c=a.t===4?bc(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else if(c.t===2&&d===c.c.length){c.c+=a.t===4?bc(a.c,b,e):b===0&&a.c.length===e?a.c:a.c.slice(b,b+e);c.t=c.c.length===c.l?0:2}else{if(c.t!==4)a5(c);var
g=a.c,h=c.c;if(a.t===4)if(d<=b)for(var
f=0;f<e;f++)h[d+f]=g[b+f];else
for(var
f=e-1;f>=0;f--)h[d+f]=g[b+f];else{var
i=Math.min(e,g.length-b);for(var
f=0;f<i;f++)h[d+f]=g.charCodeAt(b+f);for(;f<e;f++)h[d+f]=0}}return 0}function
az(a,b){if(a===0)return f;if(b.repeat)return b.repeat(a);var
d=f,c=0;for(;;){if(a&1)d+=b;a>>=1;if(a===0)return d;b+=b;c++;if(c===9)b.slice(0,1)}}function
a6(a){if(a.t===2)a.c+=az(a.l-a.c.length,"\0");else
a.c=bc(a.c,0,a.c.length);a.t=0}function
b7(a){if(a.length<24){for(var
b=0;b<a.length;b++)if(a.charCodeAt(b)>bF)return false;return true}else
return!/[^\x00-\x7f]/.test(a)}function
dM(a){for(var
k=f,d=f,h,g,i,b,c=0,j=a.length;c<j;c++){g=a.charCodeAt(c);if(g<P){for(var
e=c+1;e<j&&(g=a.charCodeAt(e))<P;e++);if(e-c>cD){d.slice(0,1);k+=d;d=f;k+=a.slice(c,e)}else
d+=a.slice(c,e);if(e===j)break;c=e}b=1;if(++c<j&&((i=a.charCodeAt(c))&-64)===aK){h=i+(g<<6);if(g<c5){b=h-0x3080;if(b<P)b=1}else{b=2;if(++c<j&&((i=a.charCodeAt(c))&-64)===aK){h=i+(h<<6);if(g<c4){b=h-0xe2080;if(b<c0||b>=0xd7ff&&b<0xe000)b=2}else{b=3;if(++c<j&&((i=a.charCodeAt(c))&-64)===aK&&g<0xf5){b=i-0x3c82080+(h<<6);if(b<0x10000||b>0x10ffff)b=3}}}}}if(b<4){c-=b;d+="\ufffd"}else if(b>T)d+=String.fromCharCode(0xd7c0+(b>>10),cq+(b&0x3ff));else
d+=String.fromCharCode(b);if(d.length>aH){d.slice(0,1);k+=d;d=f}}return k+d}function
aa(a,b,c){this.t=a;this.c=b;this.l=c}aa.prototype.toString=function(){switch(this.t){case
9:case
8:return this.c;case
4:case
2:a6(this);case
0:if(b7(this.c))this.t=9;else
this.t=8;return this.c}};aa.prototype.toUtf16=function(){var
a=this.toString();if(this.t===9)return a;return dM(a)};aa.prototype.slice=function(){var
a=this.t===4?this.c.slice():this.c;return new
aa(this.t,a,this.l)};function
dp(a){return new
aa(0,a,a.length)}function
aj(a){return a}function
aq(a){return dp(aj(a))}function
a3(a,b,c,d,e){ai(aq(a),b,c,d,e);return 0}var
dO={};function
g$(a){if(dO[a])return dO[a];var
b=c.process;if(b&&b.env&&b.env[a]!==undefined)return b.env[a];if(c.jsoo_env&&typeof
c.jsoo_env[a]==="string")return c.jsoo_env[a]}var
a$=0;(function(){var
c=g$("OCAMLRUNPARAM");if(c!==undefined){var
b=c.split(",");for(var
a=0;a<b.length;a++)if(b[a]==="b"){a$=1;break}else if(b[a].startsWith("b="))a$=+b[a].slice(2);else
continue}}());var
g3=a$,z=[0];function
gy(a,b){if(!a.js_error||b||a[0]===t)a.js_error=new
c.Error("Js exception containing backtrace");return a}function
h(a,b){return a$&&g3?gy(a,b):a}function
g2(a,b){throw h([0,a,b])}function
N(a){return a}function
b3(a,b){g2(a,N(b))}function
g(a){b3(z.Invalid_argument,a)}function
gs(){g(bw)}function
o(a,b,c){c&=$;if(a.t!==4){if(b===a.c.length){a.c+=String.fromCharCode(c);if(b+1===a.l)a.t=0;return 0}a5(a)}a.c[b]=c;return 0}function
ar(a,b,c){if(b>>>0>=a.l)gs();return o(a,b,c)}function
bR(a,b){switch(a.t&6){case
0:return a.c.charCodeAt(b);case
2:if(b>=a.c.length)return 0;return a.c.charCodeAt(b);case
4:return a.c[b]}}function
as(d,c){var
f=d.l>=0?d.l:d.l=d.length,e=c.length,b=f-e;if(b===0)return d.apply(null,c);else if(b<0){var
a=d.apply(null,c.slice(0,f));if(typeof
a!=="function")return a;return as(a,c.slice(f))}else{switch(b){case
1:{var
a=function(a){var
f=new
Array(e+1);for(var
b=0;b<e;b++)f[b]=c[b];f[e]=a;return d.apply(null,f)};break}case
2:{var
a=function(a,b){var
g=new
Array(e+2);for(var
f=0;f<e;f++)g[f]=c[f];g[e]=a;g[e+1]=b;return d.apply(null,g)};break}default:var
a=function(){var
e=arguments.length===0?1:arguments.length,b=new
Array(c.length+e);for(var
a=0;a<c.length;a++)b[a]=c[a];for(var
a=0;a<arguments.length;a++)b[c.length+a]=arguments[a];return as(d,b)}}a.l=b;return a}}function
a2(){g(bw)}function
dq(a,b){if(b>>>0>=a.length-1)a2();return a}function
gu(a){if(Number.isFinite(a)){if(Math.abs(a)>=2.2250738585072014e-308)return 0;if(a!==0)return 1;return 2}return Number.isNaN(a)?4:3}function
gw(){return[0]}function
y(a){if(a<0)g("Bytes.create");return new
aa(a?2:9,f,a)}function
gz(a,b,c,d){if(c>0)if(b===0&&(c>=a.l||a.t===2&&c>=a.c.length))if(d===0){a.c=f;a.t=2}else{a.c=az(c,String.fromCharCode(d));a.t=c===a.l?0:2}else{if(a.t!==4)a5(a);for(c+=b;b<c;b++)a.c[b]=d}return 0}function
b2(a){a=aj(a);var
e=a.length;if(e>31)g("format_int: format too long");var
b={justify:ax,signstyle:an,filler:_,alternate:false,base:0,signedconv:false,width:0,uppercase:false,sign:1,prec:-1,conv:"f"};for(var
d=0;d<e;d++){var
c=a.charAt(d);switch(c){case"-":b.justify=an;break;case"+":case" ":b.signstyle=c;break;case"0":b.filler=G;break;case"#":b.alternate=true;break;case"1":case"2":case"3":case"4":case"5":case"6":case"7":case"8":case"9":b.width=0;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.width=b.width*10+c;d++}d--;break;case".":b.prec=0;d++;while(c=a.charCodeAt(d)-48,c>=0&&c<=9){b.prec=b.prec*10+c;d++}d--;break;case"d":case"i":b.signedconv=true;b.base=10;break;case"u":b.base=10;break;case"x":b.base=16;break;case"X":b.base=16;b.uppercase=true;break;case"o":b.base=8;break;case"e":case"f":case"g":b.signedconv=true;b.conv=c;break;case"E":case"F":case"G":b.signedconv=true;b.uppercase=true;b.conv=c.toLowerCase();break}}return b}function
bT(a,b){if(a.uppercase)b=b.toUpperCase();var
e=b.length;if(a.signedconv&&(a.sign<0||a.signstyle!==an))e++;if(a.alternate){if(a.base===8)e+=1;if(a.base===16)e+=2}var
c=f;if(a.justify===ax&&a.filler===_)for(var
d=e;d<a.width;d++)c+=_;if(a.signedconv)if(a.sign<0)c+=an;else if(a.signstyle!==an)c+=a.signstyle;if(a.alternate&&a.base===8)c+=G;if(a.alternate&&a.base===16)c+=a.uppercase?"0X":cL;if(a.justify===ax&&a.filler===G)for(var
d=e;d<a.width;d++)c+=G;c+=b;if(a.justify===an)for(var
d=e;d<a.width;d++)c+=_;return N(c)}function
bU(a,b){function
j(a,b){if(Math.abs(a)<1.0)return a.toFixed(b);else{var
c=Number.parseInt(a.toString().split(ax)[1]);if(c>20){c-=20;a/=Math.pow(10,c);a+=new
Array(c+1).join(G);if(b>0)a=a+ao+new
Array(b+1).join(G);return a}else
return a.toFixed(b)}}var
c,f=b2(a),e=f.prec<0?6:f.prec;if(b<0||b===0&&1/b===Number.NEGATIVE_INFINITY){f.sign=-1;b=-b}if(Number.isNaN(b)){c=bC;f.filler=_}else if(!Number.isFinite(b)){c="inf";f.filler=_}else
switch(f.conv){case"e":var
c=b.toExponential(e),d=c.length;if(c.charAt(d-3)===bJ)c=c.slice(0,d-1)+G+c.slice(d-1);break;case"f":c=j(b,e);break;case"g":e=e?e:1;c=b.toExponential(e-1);var
i=c.indexOf(bJ),h=+c.slice(i+1);if(h<-4||b>=1e21||b.toFixed(0).length>e){var
d=i-1;while(c.charAt(d)===G)d--;if(c.charAt(d)===ao)d--;c=c.slice(0,d+1)+c.slice(i);d=c.length;if(c.charAt(d-3)===bJ)c=c.slice(0,d-1)+G+c.slice(d-1);break}else{var
g=e;if(h<0){g-=h+1;c=b.toFixed(g)}else
while(c=b.toFixed(g),c.length>e+1)g--;if(g){var
d=c.length-1;while(c.charAt(d)===G)d--;if(c.charAt(d)===ao)d--;c=c.slice(0,d+1)}}break}return bT(f,c)}function
a7(a,b){if(aj(a)===bv)return N(f+b);var
c=b2(a);if(b<0)if(c.signedconv){c.sign=-1;b=-b}else
b>>>=0;var
d=b.toString(c.base);if(c.prec>=0){c.filler=_;var
e=c.prec-d.length;if(e>0)d=az(e,G)+d}return bT(c,d)}var
g0=0;function
dv(){return g0++}function
at(a){if(!z.Failure)z.Failure=[t,N(bM),-3];b3(z.Failure,a)}function
dB(a){if(b7(a))return a;return dM(a)}function
aQ(){return typeof
c.process!=="undefined"&&typeof
c.process.versions!=="undefined"&&typeof
c.process.versions.node!=="undefined"}function
hb(){function
a(a){if(a.charAt(0)===Y)return[f,a.slice(1)];return}function
b(a){var
h=/^([a-zA-Z]:|[\\/]{2}[^\\/]+[\\/]+[^\\/]+)?([\\/])?([\s\S]*?)$/,b=h.exec(a),c=b[1]||f,e=c.length>0&&c.charAt(1)!==":";if(b[2]||e){var
d=b[1]||f,g=b[2]||f;return[d,a.slice(d.length+g.length)]}return}return aQ()&&c.process&&c.process.platform?c.process.platform==="win32"?b:a:a}var
b8=hb();function
dK(a){return a.slice(-1)!==Y?a+Y:a}if(aQ()&&c.process&&c.process.cwd)var
aM=c.process.cwd().replace(/\\/g,Y);else
var
aM="/static";aM=dK(aM);function
gT(a){a=dB(a);if(!b8(a))a=aM+a;var
e=b8(a),d=e[1].split(/[/\\]/),b=[];for(var
c=0;c<d.length;c++)switch(d[c]){case"..":if(b.length>1)b.pop();break;case".":break;case"":break;default:b.push(d[c]);break}b.unshift(e[0]);b.orig=a;return b}function
g8(a){for(var
g=f,c=g,b,i,d=0,h=a.length;d<h;d++){b=a.charCodeAt(d);if(b<P){for(var
e=d+1;e<h&&(b=a.charCodeAt(e))<P;e++);if(e-d>cD){c.slice(0,1);g+=c;c=f;g+=a.slice(d,e)}else
c+=a.slice(d,e);if(e===h)break;d=e}if(b<c0){c+=String.fromCharCode(0xc0|b>>6);c+=String.fromCharCode(P|b&aw)}else if(b<0xd800||b>=cK)c+=String.fromCharCode(c5|b>>12,P|b>>6&aw,P|b&aw);else if(b>=0xdbff||d+1===h||(i=a.charCodeAt(d+1))<cq||i>cK)c+="\xef\xbf\xbd";else{d++;b=(b<<10)+i-0x35fdc00;c+=String.fromCharCode(c4|b>>18,P|b>>12&aw,P|b>>6&aw,P|b&aw)}if(c.length>aH){c.slice(0,1);g+=c;c=f}}return g+c}function
R(a){return b7(a)?N(a):N(g8(a))}var
hc=["E2BIG","EACCES","EAGAIN",bu,"EBUSY","ECHILD","EDEADLK","EDOM",c2,"EFAULT","EFBIG","EINTR","EINVAL","EIO","EISDIR","EMFILE","EMLINK","ENAMETOOLONG","ENFILE","ENODEV",bI,"ENOEXEC","ENOLCK","ENOMEM","ENOSPC","ENOSYS",bL,cz,"ENOTTY","ENXIO","EPERM","EPIPE","ERANGE","EROFS","ESPIPE","ESRCH","EXDEV","EWOULDBLOCK","EINPROGRESS","EALREADY","ENOTSOCK","EDESTADDRREQ","EMSGSIZE","EPROTOTYPE","ENOPROTOOPT","EPROTONOSUPPORT","ESOCKTNOSUPPORT","EOPNOTSUPP","EPFNOSUPPORT","EAFNOSUPPORT","EADDRINUSE","EADDRNOTAVAIL","ENETDOWN","ENETUNREACH","ENETRESET","ECONNABORTED","ECONNRESET","ENOBUFS","EISCONN","ENOTCONN","ESHUTDOWN","ETOOMANYREFS","ETIMEDOUT","ECONNREFUSED","EHOSTDOWN","EHOSTUNREACH","ELOOP","EOVERFLOW"];function
ae(a,b,c,d){var
e=hc.indexOf(a);if(e<0){if(d==null)d=-9999;e=[0,d]}var
g=[e,R(b||f),R(c||f)];return g}var
dH={};function
al(a){return dH[a]}function
ad(a,b){throw h([0,a].concat(b))}function
b0(a){return a
instanceof
aa}function
b1(a){return typeof
a==="string"&&!/[^\x00-\xff]/.test(a)}function
bQ(a){if(!(a
instanceof
Uint8Array))a=new
Uint8Array(a);return new
aa(4,a,a.length)}function
e(a){b3(z.Sys_error,a)}function
dI(a){e(a+aJ)}function
dL(a){if(a.t!==4)a5(a);return a.c}function
V(a){return a.l}function
dh(){}function
B(a){this.data=a}B.prototype=new
dh();B.prototype.constructor=B;B.prototype.truncate=function(a){var
b=this.data;this.data=y(a|0);ai(b,0,this.data,0,a)};B.prototype.length=function(){return V(this.data)};B.prototype.write=function(a,b,c,d){var
e=this.length();if(a+d>=e){var
f=y(a+d),g=this.data;this.data=f;ai(g,0,this.data,0,e)}ai(bQ(b),c,this.data,a,d);return 0};B.prototype.read=function(a,b,c,d){var
e=this.length();if(a+d>=e)d=e-a;if(d){var
f=y(d|0);ai(this.data,a,f,0,d);b.set(dL(f),c)}return d};function
ap(a,b,c){this.file=b;this.name=a;this.flags=c}ap.prototype.err_closed=function(){e(this.name+cv)};ap.prototype.length=function(){if(this.file)return this.file.length();this.err_closed()};ap.prototype.write=function(a,b,c,d){if(this.file)return this.file.write(a,b,c,d);this.err_closed()};ap.prototype.read=function(a,b,c,d){if(this.file)return this.file.read(a,b,c,d);this.err_closed()};ap.prototype.close=function(){this.file=undefined};function
u(a,b){this.content={};this.root=a;this.lookupFun=b}u.prototype.nm=function(a){return this.root+a};u.prototype.create_dir_if_needed=function(a){var
d=a.split(Y),c=f;for(var
b=0;b<d.length-1;b++){c+=d[b]+Y;if(this.content[c])continue;this.content[c]=Symbol("directory")}};u.prototype.slash=function(a){return/\/$/.test(a)?a:a+Y};u.prototype.lookup=function(a){if(!this.content[a]&&this.lookupFun){var
b=this.lookupFun(N(this.root),N(a));if(b!==0){this.create_dir_if_needed(a);this.content[a]=new
B(aq(b[1]))}}};u.prototype.exists=function(a,b){if(a===f)return 1;var
c=this.slash(a);if(this.content[c])return 1;if(!b)this.lookup(a);return this.content[a]?1:0};u.prototype.isFile=function(a){return this.exists(a)&&!this.is_dir(a)?1:0};u.prototype.mkdir=function(a,b,c){var
g=c&&al(a1);if(this.exists(a))if(g)ad(g,ae(c2,bD,this.nm(a)));else
e(a+": File exists");var
d=/^(.*)\/[^/]+/.exec(a);d=d&&d[1]||f;if(!this.exists(d))if(g)ad(g,ae(bI,bD,this.nm(d)));else
e(d+aJ);if(!this.is_dir(d))if(g)ad(g,ae(bL,bD,this.nm(d)));else
e(d+bx);this.create_dir_if_needed(this.slash(a))};u.prototype.rmdir=function(a,b){var
c=b&&al(a1),d=a===f?f:this.slash(a),h=new
RegExp(db+d+cS);if(!this.exists(a))if(c)ad(c,ae(bI,bB,this.nm(a)));else
e(a+aJ);if(!this.is_dir(a))if(c)ad(c,ae(bL,bB,this.nm(a)));else
e(a+bx);for(var
g
in
this.content)if(g.match(h))if(c)ad(c,ae(cz,bB,this.nm(a)));else
e(this.nm(a)+": Directory not empty");delete
this.content[d]};u.prototype.readdir=function(a){var
h=a===f?f:this.slash(a);if(!this.exists(a))e(a+aJ);if(!this.is_dir(a))e(a+bx);var
i=new
RegExp(db+h+cS),d={},c=[];for(var
g
in
this.content){var
b=g.match(i);if(b&&!d[b[1]]){d[b[1]]=true;c.push(b[1])}}return c};u.prototype.opendir=function(a,b){var
c=b&&al(a1),d=this.readdir(a),f=false,g=0;return{readSync:function(){if(f)if(c)ad(c,ae(bu,c9,this.nm(a)));else
e(a+cJ);if(g===d.length)return null;var
b=d[g];g++;return{name:b}},closeSync:function(){if(f)if(c)ad(c,ae(bu,c9,this.nm(a)));else
e(a+cJ);f=true;d=[]}}};u.prototype.is_dir=function(a){if(a===f)return true;var
b=this.slash(a);return this.content[b]?1:0};u.prototype.unlink=function(a){if(!this.exists(a,true))e(a+aJ);delete
this.content[a];return 0};u.prototype.open=function(a,b){var
c;if(b.rdonly&&b.wronly)e(this.nm(a)+bG);if(b.text&&b.binary)e(this.nm(a)+by);this.lookup(a);if(this.content[a]){if(this.is_dir(a))e(this.nm(a)+cw);if(b.create&&b.excl)e(this.nm(a)+bH);c=this.content[a];if(b.truncate)c.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
B(y(0));c=this.content[a]}else
dI(this.nm(a));return new
ap(this.nm(a),c,b)};u.prototype.open=function(a,b){var
c;if(b.rdonly&&b.wronly)e(this.nm(a)+bG);if(b.text&&b.binary)e(this.nm(a)+by);this.lookup(a);if(this.content[a]){if(this.is_dir(a))e(this.nm(a)+cw);if(b.create&&b.excl)e(this.nm(a)+bH);c=this.content[a];if(b.truncate)c.truncate()}else if(b.create){this.create_dir_if_needed(a);this.content[a]=new
B(y(0));c=this.content[a]}else
dI(this.nm(a));return new
ap(this.nm(a),c,b)};u.prototype.register=function(a,b){var
c;if(this.content[a])e(this.nm(a)+bH);if(b0(b))c=new
B(b);if(b1(b))c=new
B(aq(b));else if(Array.isArray(b))c=new
B(bQ(b));else if(typeof
b==="string")c=new
B(dp(b));else if(b.toString){var
d=aq(R(b.toString()));c=new
B(d)}if(c){this.create_dir_if_needed(a);this.content[a]=c}else
e(this.nm(a)+" : registering file with invalid content type")};u.prototype.constructor=u;function
D(a){return a.length}function
bb(a,b){return a.charCodeAt(b)}function
hg(a){var
d=D(a),c=new
Uint8Array(d),b=0;for(;b<d;b++)c[b]=bb(a,b);return c}function
Q(a,b){this.fs=require(bN);this.fd=a;this.flags=b}Q.prototype=new
dh();Q.prototype.constructor=Q;Q.prototype.truncate=function(a){try{this.fs.ftruncateSync(this.fd,a|0)}catch(f){e(f.toString())}};Q.prototype.length=function(){try{return this.fs.fstatSync(this.fd).size}catch(f){e(f.toString())}};Q.prototype.write=function(a,b,c,d){try{if(this.flags.isCharacterDevice)this.fs.writeSync(this.fd,b,c,d);else
this.fs.writeSync(this.fd,b,c,d,a)}catch(f){e(f.toString())}return 0};Q.prototype.read=function(a,b,c,d){try{if(this.flags.isCharacterDevice)var
f=this.fs.readSync(this.fd,b,c,d);else
var
f=this.fs.readSync(this.fd,b,c,d,a);return f}catch(f){e(f.toString())}};Q.prototype.close=function(){try{this.fs.closeSync(this.fd);return 0}catch(f){e(f.toString())}};function
b(a){this.fs=require(bN);this.root=a}b.prototype.nm=function(a){return this.root+a};b.prototype.exists=function(a){try{return this.fs.existsSync(this.nm(a))?1:0}catch(f){return 0}};b.prototype.isFile=function(a){try{return this.fs.statSync(this.nm(a)).isFile()?1:0}catch(f){e(f.toString())}};b.prototype.mkdir=function(a,b,c){try{this.fs.mkdirSync(this.nm(a),{mode:b});return 0}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.rmdir=function(a,b){try{this.fs.rmdirSync(this.nm(a));return 0}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.readdir=function(a,b){try{return this.fs.readdirSync(this.nm(a))}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.is_dir=function(a){try{return this.fs.statSync(this.nm(a)).isDirectory()?1:0}catch(f){e(f.toString())}};b.prototype.unlink=function(a,b){try{this.fs.unlinkSync(this.nm(a));return 0}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.open=function(a,b,c){var
d=require("node:constants"),e=0;for(var
h
in
b)switch(h){case"rdonly":e|=d.O_RDONLY;break;case"wronly":e|=d.O_WRONLY;break;case"append":e|=d.O_WRONLY|d.O_APPEND;break;case"create":e|=d.O_CREAT;break;case"truncate":e|=d.O_TRUNC;break;case"excl":e|=d.O_EXCL;break;case"binary":e|=d.O_BINARY;break;case"text":e|=d.O_TEXT;break;case"nonblock":e|=d.O_NONBLOCK;break}try{var
f=this.fs.openSync(this.nm(a),e),g=this.fs.lstatSync(this.nm(a)).isCharacterDevice();b.isCharacterDevice=g;return new
Q(f,b)}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.rename=function(a,b,c){try{this.fs.renameSync(this.nm(a),this.nm(b))}catch(f){this.raise_nodejs_error(f,c)}};b.prototype.stat=function(a,b){try{var
c=this.fs.statSync(this.nm(a));return this.stats_from_js(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.lstat=function(a,b){try{var
c=this.fs.lstatSync(this.nm(a));return this.stats_from_js(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.symlink=function(a,b,c,d){try{this.fs.symlinkSync(this.nm(b),this.nm(c),a?"dir":"file");return 0}catch(f){this.raise_nodejs_error(f,d)}};b.prototype.readlink=function(a,b){try{var
c=this.fs.readlinkSync(this.nm(a),"utf8");return R(c)}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.opendir=function(a,b){try{return this.fs.opendirSync(this.nm(a))}catch(f){this.raise_nodejs_error(f,b)}};b.prototype.raise_nodejs_error=function(a,b){var
c=al(a1);if(b&&c){var
d=ae(a.code,a.syscall,a.path,a.errno);ad(c,d)}else
e(a.toString())};b.prototype.stats_from_js=function(a){var
b;if(a.isFile())b=0;else if(a.isDirectory())b=1;else if(a.isCharacterDevice())b=2;else if(a.isBlockDevice())b=3;else if(a.isSymbolicLink())b=4;else if(a.isFIFO())b=5;else if(a.isSocket())b=6;return[0,a.dev,a.ino,b,a.mode,a.nlink,a.uid,a.gid,a.rdev,a.size,a.atimeMs,a.mtimeMs,a.ctimeMs]};b.prototype.constructor=b;function
dx(a){var
b=b8(a);if(!b)return;return b[0]+Y}var
ba=dx(aM)||at("unable to compute caml_root"),aA=[];if(aQ())aA.push({path:ba,device:new
b(ba)});else
aA.push({path:ba,device:new
u(ba)});aA.push({path:cO,device:new
u(cO)});function
dQ(a){var
i=gT(a),a=i.join(Y),h=dK(a),d;for(var
g=0;g<aA.length;g++){var
c=aA[g];if(h.search(c.path)===0&&(!d||d.path.length<c.path.length))d={path:c.path,device:c.device,rest:a.slice(c.path.length,a.length)}}if(!d&&aQ()){var
f=dx(a);if(f&&f.match(/^[a-zA-Z]:\/$/)){var
c={path:f,device:new
b(f)};aA.push(c);d={path:c.path,device:c.device,rest:a.slice(c.path.length,a.length)}}}if(d)return d;e("no device found for "+h)}function
gx(a,b){var
c=dQ(a);if(!c.device.register)at("cannot register file");c.device.register(c.rest,b);return 0}function
dN(a,b){var
a=N(a),b=N(b);return gx(a,b)}function
gB(){var
b=c.jsoo_fs_tmp;if(b)for(var
a=0;a<b.length;a++)dN(b[a].name,b[a].content);c.jsoo_create_file=dN;c.jsoo_fs_tmp=[];return 0}function
dw(){return[0]}function
gD(a,b,c){if(!Number.isFinite(a)){if(Number.isNaN(a))return R(bC);return R(a>0?c7:"-infinity")}var
k=a===0&&1/a===Number.NEGATIVE_INFINITY?1:a>=0?0:1;if(k)a=-a;var
e=0;if(a===0);else if(a<1)while(a<1&&e>-1022){a*=2;e--}else
while(a>=2){a/=2;e++}var
l=e<0?f:ax,g=f;if(k)g=an;else
switch(c){case
43:g=ax;break;case
32:g=_;break;default:break}if(b>=0&&b<13){var
i=Math.pow(2,b*4);a=Math.round(a*i)/i}var
d=a.toString(16);if(b>=0){var
j=d.indexOf(ao);if(j<0)d+=ao+az(b,G);else{var
h=j+1+b;if(d.length<h)d+=az(h-d.length,G);else
d=d.slice(0,h)}}return R(g+cL+d+"p"+l+e.toString(10))}function
gK(a){return+a.isZero()}var
dz=Math.pow(2,-24);function
g1(a){throw a}function
dJ(){g1(z.Division_by_zero)}function
d(a,b,c){this.lo=a&Z;this.mi=b&Z;this.hi=c&T}d.prototype.caml_custom="_j";d.prototype.copy=function(){return new
d(this.lo,this.mi,this.hi)};d.prototype.ucompare=function(a){if(this.hi>a.hi)return 1;if(this.hi<a.hi)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};d.prototype.compare=function(a){var
b=this.hi<<16,c=a.hi<<16;if(b>c)return 1;if(b<c)return-1;if(this.mi>a.mi)return 1;if(this.mi<a.mi)return-1;if(this.lo>a.lo)return 1;if(this.lo<a.lo)return-1;return 0};d.prototype.neg=function(){var
a=-this.lo,b=-this.mi+(a>>24),c=-this.hi+(b>>24);return new
d(a,b,c)};d.prototype.add=function(a){var
b=this.lo+a.lo,c=this.mi+a.mi+(b>>24),e=this.hi+a.hi+(c>>24);return new
d(b,c,e)};d.prototype.sub=function(a){var
b=this.lo-a.lo,c=this.mi-a.mi+(b>>24),e=this.hi-a.hi+(c>>24);return new
d(b,c,e)};d.prototype.mul=function(a){var
b=this.lo*a.lo,c=(b*dz|0)+this.mi*a.lo+this.lo*a.mi,e=(c*dz|0)+this.hi*a.lo+this.mi*a.mi+this.lo*a.hi;return new
d(b,c,e)};d.prototype.isZero=function(){return(this.lo|this.mi|this.hi)===0};d.prototype.isNeg=function(){return this.hi<<16<0};d.prototype.and=function(a){return new
d(this.lo&a.lo,this.mi&a.mi,this.hi&a.hi)};d.prototype.or=function(a){return new
d(this.lo|a.lo,this.mi|a.mi,this.hi|a.hi)};d.prototype.xor=function(a){return new
d(this.lo^a.lo,this.mi^a.mi,this.hi^a.hi)};d.prototype.shift_left=function(a){a=a&63;if(a===0)return this;if(a<24)return new
d(this.lo<<a,this.mi<<a|this.lo>>24-a,this.hi<<a|this.mi>>24-a);if(a<48)return new
d(0,this.lo<<a-24,this.mi<<a-24|this.lo>>48-a);return new
d(0,0,this.lo<<a-48)};d.prototype.shift_right_unsigned=function(a){a=a&63;if(a===0)return this;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|this.hi<<24-a,this.hi>>a);if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi>>a-24,0);return new
d(this.hi>>a-48,0,0)};d.prototype.shift_right=function(a){a=a&63;if(a===0)return this;var
c=this.hi<<16>>16;if(a<24)return new
d(this.lo>>a|this.mi<<24-a,this.mi>>a|c<<24-a,this.hi<<16>>a>>>16);var
b=this.hi<<16>>31;if(a<48)return new
d(this.mi>>a-24|this.hi<<48-a,this.hi<<16>>a-24>>16,b&T);return new
d(this.hi<<16>>a-32,b,b)};d.prototype.lsl1=function(){this.hi=this.hi<<1|this.mi>>23;this.mi=(this.mi<<1|this.lo>>23)&Z;this.lo=this.lo<<1&Z};d.prototype.lsr1=function(){this.lo=(this.lo>>>1|this.mi<<23)&Z;this.mi=(this.mi>>>1|this.hi<<23)&Z;this.hi=this.hi>>>1};d.prototype.udivmod=function(a){var
e=0,c=this.copy(),b=a.copy(),f=new
d(0,0,0);while(c.ucompare(b)>0){e++;b.lsl1()}while(e>=0){e--;f.lsl1();if(c.ucompare(b)>=0){f.lo++;c=c.sub(b)}b.lsr1()}return{quotient:f,modulus:c}};d.prototype.div=function(a){var
b=this;if(a.isZero())dJ();var
d=b.hi^a.hi;if(b.hi&U)b=b.neg();if(a.hi&U)a=a.neg();var
c=b.udivmod(a).quotient;if(d&U)c=c.neg();return c};d.prototype.mod=function(a){var
b=this;if(a.isZero())dJ();var
d=b.hi;if(b.hi&U)b=b.neg();if(a.hi&U)a=a.neg();var
c=b.udivmod(a).modulus;if(d&U)c=c.neg();return c};d.prototype.toInt=function(){return this.lo|this.mi<<24};d.prototype.toFloat=function(){return(this.hi<<16)*Math.pow(2,32)+this.mi*Math.pow(2,24)+this.lo};d.prototype.toArray=function(){return[this.hi>>8,this.hi&$,this.mi>>16,this.mi>>8&$,this.mi&$,this.lo>>16,this.lo>>8&$,this.lo&$]};d.prototype.lo32=function(){return this.lo|(this.mi&$)<<24};d.prototype.hi32=function(){return this.mi>>>8&T|this.hi<<16};function
gN(a){return new
d(a&Z,a>>24&Z,a>>31&T)}function
gO(a){return a.toInt()}function
gJ(a){return+a.isNeg()}function
gM(a){return a.neg()}function
gH(a,b){var
c=b2(a);if(c.signedconv&&gJ(b)){c.sign=-1;b=gM(b)}var
d=f,i=gN(c.base),h="0123456789abcdef";do{var
g=b.udivmod(i);b=g.quotient;d=h.charAt(gO(g.modulus))+d}while(!gK(b));if(c.prec>=0){c.filler=_;var
e=c.prec-d.length;if(e>0)d=az(e,G)+d}return bT(c,d)}var
a4=as;function
dA(a){return function(){var
d=arguments.length;if(d>0){var
c=new
Array(d);for(var
b=0;b<d;b++)c[b]=arguments[b]}else
c=[undefined];var
e=a4(a,c);return e
instanceof
Function?dA(e):e}}function
gU(){return 0}var
ak=new
Array();function
dC(a){return ak[a]}function
ac(a){var
b=dC(a);if(!b.opened)e("Cannot flush a closed channel");if(!b.buffer||b.buffer_curr===0)return 0;if(b.output)b.output(bc(b.buffer,0,b.buffer_curr));else
b.file.write(b.offset,b.buffer,0,b.buffer_curr);b.offset+=b.buffer_curr;b.buffer_curr=0;return 0}function
g7(a,b){if(b.name)try{var
d=require(bN),c=d.openSync(b.name,"rs");return new
Q(c,b)}catch(f){}return new
Q(a,b)}var
bd=new
Array(3);function
aL(a,b){B.call(this,y(0));this.log=function(a){return 0};if(a===1&&typeof
console.log==="function")this.log=console.log;else if(a===2&&typeof
console.error==="function")this.log=console.error;else if(typeof
console.log==="function")this.log=console.log;this.flags=b}aL.prototype.length=function(){return 0};aL.prototype.write=function(a,b,c,d){if(this.log){if(d>0&&c>=0&&c+d<=b.length&&b[c+d-1]===10)d--;var
f=y(d);ai(bQ(b),c,f,0,d);this.log(f.toUtf16());return 0}e(this.fd+cv)};aL.prototype.read=function(a,b,c,d){e(this.fd+": file descriptor is write only")};aL.prototype.close=function(){this.log=undefined};function
be(a,b){if(b===undefined)b=bd.length;bd[b]=a;return b|0}function
hf(a,b,c){var
d={};while(b){switch(b[1]){case
0:d.rdonly=1;break;case
1:d.wronly=1;break;case
2:d.append=1;break;case
3:d.create=1;break;case
4:d.truncate=1;break;case
5:d.excl=1;break;case
6:d.binary=1;break;case
7:d.text=1;break;case
8:d.nonblock=1;break}b=b[2]}if(d.rdonly&&d.wronly)e(aj(a)+bG);if(d.text&&d.binary)e(aj(a)+by);var
f=dQ(a),g=f.device.open(f.rest,d);return be(g,undefined)}(function(){function
a(a,b){return aQ()?g7(a,b):new
aL(a,b)}be(a(0,{rdonly:1,altname:"/dev/stdin",isCharacterDevice:true}),0);be(a(1,{buffered:2,wronly:1,isCharacterDevice:true}),1);be(a(2,{buffered:2,wronly:1,isCharacterDevice:true}),2)}());function
gV(a){var
b=bd[a];if(b.flags.wronly)e(c6+a+" is writeonly");var
d=null,c={file:b,offset:b.flags.append?b.length():0,fd:a,opened:true,out:false,buffer_curr:0,buffer_max:0,buffer:new
Uint8Array(c_),refill:d};ak[c.fd]=c;return c.fd}function
dD(a){var
b=bd[a];if(b.flags.rdonly)e(c6+a+" is readonly");var
d=b.flags.buffered!==undefined?b.flags.buffered:1,c={file:b,offset:b.flags.append?b.length():0,fd:a,opened:true,out:true,buffer_curr:0,buffer:new
Uint8Array(c_),buffered:d};ak[c.fd]=c;return c.fd}function
gW(){var
b=0;for(var
a=0;a<ak.length;a++)if(ak[a]&&ak[a].opened&&ak[a].out)b=[0,ak[a].fd,b];return b}function
gY(a,b,c,d){var
f=dC(a);if(!f.opened)e("Cannot output to a closed channel");b=b.subarray(c,c+d);if(f.buffer_curr+b.length>f.buffer.length){var
h=new
Uint8Array(f.buffer_curr+b.length);h.set(f.buffer);f.buffer=h}switch(f.buffered){case
0:f.buffer.set(b,f.buffer_curr);f.buffer_curr+=b.length;ac(a);break;case
1:f.buffer.set(b,f.buffer_curr);f.buffer_curr+=b.length;if(f.buffer_curr>=f.buffer.length)ac(a);break;case
2:var
g=b.lastIndexOf(10);if(g<0){f.buffer.set(b,f.buffer_curr);f.buffer_curr+=b.length;if(f.buffer_curr>=f.buffer.length)ac(a)}else{f.buffer.set(b.subarray(0,g+1),f.buffer_curr);f.buffer_curr+=g+1;ac(a);f.buffer.set(b.subarray(g+1),f.buffer_curr);f.buffer_curr+=b.length-g-1}break}return 0}function
gX(a,b,c,d){var
b=dL(b);return gY(a,b,c,d)}function
dE(a,b,c,d){return gX(a,aq(b),c,d)}function
dF(a,b){var
c=N(String.fromCharCode(b));dE(a,c,0,1);return 0}function
gR(a){return a===245?1:0}var
ha=Math.log2&&Math.log2(1.1235582092889474e307)===1020;function
g_(a){if(ha)return Math.floor(Math.log2(a));var
b=0;if(a===0)return Number.NEGATIVE_INFINITY;if(a>=1)while(a>=2){a/=2;b++}else
while(a<1){a*=2;b--}return b}function
bV(a){var
b=new
Float32Array(1);b[0]=a;var
c=new
Int32Array(b.buffer);return c[0]|0}function
a9(a,b,c){return new
d(a,b,c)}function
a8(a){if(!Number.isFinite(a)){if(Number.isNaN(a))return a9(1,0,de);return a>0?a9(0,0,de):a9(0,0,0xfff0)}var
f=a===0&&1/a===Number.NEGATIVE_INFINITY?U:a>=0?0:U;if(f)a=-a;var
b=g_(a)+1023;if(b<=0){b=0;a/=Math.pow(2,-cB)}else{a/=Math.pow(2,b-cE);if(a<16){a*=2;b-=1}if(b===0)a/=2}var
d=Math.pow(2,24),c=a|0;a=(a-c)*d;var
e=a|0;a=(a-e)*d;var
g=a|0;c=c&bK|f|b<<4;return a9(g,e,c)}function
aO(a){return a.toArray()}function
dn(a,b,c){a.write(32,b.dims.length);a.write(32,b.kind|b.layout<<8);if(b.caml_custom===a0)for(var
d=0;d<b.dims.length;d++)if(b.dims[d]<T)a.write(16,b.dims[d]);else{a.write(16,T);a.write(32,0);a.write(32,b.dims[d])}else
for(var
d=0;d<b.dims.length;d++)a.write(32,b.dims[d]);switch(b.kind){case
2:case
3:case
12:for(var
d=0;d<b.data.length;d++)a.write(8,b.data[d]);break;case
4:case
5:for(var
d=0;d<b.data.length;d++)a.write(16,b.data[d]);break;case
6:for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
8:case
9:a.write(8,0);for(var
d=0;d<b.data.length;d++)a.write(32,b.data[d]);break;case
7:for(var
d=0;d<b.data.length/2;d++){var
f=aO(b.get(d));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
1:for(var
d=0;d<b.data.length;d++){var
f=aO(a8(b.get(d)));for(var
e=0;e<8;e++)a.write(8,f[e])}break;case
0:for(var
d=0;d<b.data.length;d++){var
f=bV(b.get(d));a.write(32,f)}break;case
10:for(var
d=0;d<b.data.length/2;d++){var
e=b.get(d);a.write(32,bV(e[1]));a.write(32,bV(e[2]))}break;case
11:for(var
d=0;d<b.data.length/2;d++){var
g=b.get(d),f=aO(a8(g[1]));for(var
e=0;e<8;e++)a.write(8,f[e]);var
f=aO(a8(g[2]));for(var
e=0;e<8;e++)a.write(8,f[e])}break}c[0]=(4+b.dims.length)*4;c[1]=(4+b.dims.length)*8}function
dl(a){switch(a){case
7:case
10:case
11:return 2;default:return 1}}function
gp(a,b){var
c;switch(a){case
0:c=Float32Array;break;case
1:c=Float64Array;break;case
2:c=Int8Array;break;case
3:c=Uint8Array;break;case
4:c=Int16Array;break;case
5:c=Uint16Array;break;case
6:c=Int32Array;break;case
7:c=Int32Array;break;case
8:c=Int32Array;break;case
9:c=Int32Array;break;case
10:c=Float32Array;break;case
11:c=Float64Array;break;case
12:c=Uint8Array;break}if(!c)g("Bigarray.create: unsupported kind");var
d=new
c(b*dl(a));return d}function
bW(a){var
b=new
Int32Array(1);b[0]=a;var
c=new
Float32Array(b.buffer);return c[0]}function
aN(a){return new
d(a[7]<<0|a[6]<<8|a[5]<<16,a[4]<<0|a[3]<<8|a[2]<<16,a[1]<<0|a[0]<<8)}function
bX(a){var
f=a.lo,g=a.mi,c=a.hi,d=(c&0x7fff)>>4;if(d===2047)return(f|g|c&bK)===0?c&U?Number.NEGATIVE_INFINITY:Number.POSITIVE_INFINITY:Number.NaN;var
e=Math.pow(2,-24),b=(f*e+g)*e+(c&bK);if(d>0){b+=16;b*=Math.pow(2,d-cE)}else
b*=Math.pow(2,-cB);if(c&U)b=-b;return b}function
bP(a){var
d=a.length,c=1;for(var
b=0;b<d;b++){if(a[b]<0)g("Bigarray.create: negative dimension");c=c*a[b]}return c}function
gG(a,b){return new
d(a&Z,a>>>24&$|(b&T)<<8,b>>>16&T)}function
bY(a){return a.hi32()}function
bZ(a){return a.lo32()}var
gq=a0;function
ah(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d}ah.prototype.caml_custom=gq;ah.prototype.offset=function(a){var
c=0;if(typeof
a==="number")a=[a];if(!Array.isArray(a))g("bigarray.js: invalid offset");if(this.dims.length!==a.length)g("Bigarray.get/set: bad number of dimensions");if(this.layout===0)for(var
b=0;b<this.dims.length;b++){if(a[b]<0||a[b]>=this.dims[b])a2();c=c*this.dims[b]+a[b]}else
for(var
b=this.dims.length-1;b>=0;b--){if(a[b]<1||a[b]>this.dims[b])a2();c=c*this.dims[b]+(a[b]-1)}return c};ah.prototype.get=function(a){switch(this.kind){case
7:var
d=this.data[a*2+0],b=this.data[a*2+1];return gG(d,b);case
10:case
11:var
e=this.data[a*2+0],c=this.data[a*2+1];return[aZ,e,c];default:return this.data[a]}};ah.prototype.set=function(a,b){switch(this.kind){case
7:this.data[a*2+0]=bZ(b);this.data[a*2+1]=bY(b);break;case
10:case
11:this.data[a*2+0]=b[1];this.data[a*2+1]=b[2];break;default:this.data[a]=b;break}return 0};ah.prototype.fill=function(a){switch(this.kind){case
7:var
c=bZ(a),e=bY(a);if(c===e)this.data.fill(c);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?c:e;break;case
10:case
11:var
d=a[1],f=a[2];if(d===f)this.data.fill(d);else
for(var
b=0;b<this.data.length;b++)this.data[b]=b%2===0?d:f;break;default:this.data.fill(a);break}};ah.prototype.compare=function(a,b){if(this.layout!==a.layout||this.kind!==a.kind){var
f=this.kind|this.layout<<8,g=a.kind|a.layout<<8;return g-f}if(this.dims.length!==a.dims.length)return a.dims.length-this.dims.length;for(var
c=0;c<this.dims.length;c++)if(this.dims[c]!==a.dims[c])return this.dims[c]<a.dims[c]?-1:1;switch(this.kind){case
0:case
1:case
10:case
11:var
d,e;for(var
c=0;c<this.data.length;c++){d=this.data[c];e=a.data[c];if(d<e)return-1;if(d>e)return 1;if(d!==e){if(!b)return Number.NaN;if(!Number.isNaN(d))return 1;if(!Number.isNaN(e))return-1}}break;case
7:for(var
c=0;c<this.data.length;c+=2){if(this.data[c+1]<a.data[c+1])return-1;if(this.data[c+1]>a.data[c+1])return 1;if(this.data[c]>>>0<a.data[c]>>>0)return-1;if(this.data[c]>>>0>a.data[c]>>>0)return 1}break;case
2:case
3:case
4:case
5:case
6:case
8:case
9:case
12:for(var
c=0;c<this.data.length;c++){if(this.data[c]<a.data[c])return-1;if(this.data[c]>a.data[c])return 1}break}return 0};function
ay(a,b,c,d){this.kind=a;this.layout=b;this.dims=c;this.data=d}ay.prototype=new
ah();ay.prototype.offset=function(a){if(typeof
a!=="number")if(Array.isArray(a)&&a.length===1)a=a[0];else
g("Ml_Bigarray_c_1_1.offset");if(a<0||a>=this.dims[0])a2();return a};ay.prototype.get=function(a){return this.data[a]};ay.prototype.set=function(a,b){this.data[a]=b;return 0};ay.prototype.fill=function(a){this.data.fill(a);return 0};function
dj(a,b,c,d){var
e=dl(a);if(bP(c)*e!==d.length)g("length doesn't match dims");if(b===0&&c.length===1&&e===1)return new
ay(a,b,c,d);return new
ah(a,b,c,d)}function
dk(a,b,c){var
k=a.read32s();if(k<0||k>16)at("input_value: wrong number of bigarray dimensions");var
r=a.read32s(),l=r&$,q=r>>8&1,j=[];if(c===a0)for(var
d=0;d<k;d++){var
p=a.read16u();if(p===T){var
u=a.read32u(),v=a.read32u();if(u!==0)at("input_value: bigarray dimension overflow in 32bit");p=v}j.push(p)}else
for(var
d=0;d<k;d++)j.push(a.read32u());var
f=bP(j),h=gp(l,f),i=dj(l,q,j,h);switch(l){case
2:for(var
d=0;d<f;d++)h[d]=a.read8s();break;case
3:case
12:for(var
d=0;d<f;d++)h[d]=a.read8u();break;case
4:for(var
d=0;d<f;d++)h[d]=a.read16s();break;case
5:for(var
d=0;d<f;d++)h[d]=a.read16u();break;case
6:for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
8:case
9:var
t=a.read8u();if(t)at("input_value: cannot read bigarray with 64-bit OCaml ints");for(var
d=0;d<f;d++)h[d]=a.read32s();break;case
7:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
s=aN(g);i.set(d,s)}break;case
1:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
m=bX(aN(g));i.set(d,m)}break;case
0:for(var
d=0;d<f;d++){var
m=bW(a.read32s());i.set(d,m)}break;case
10:for(var
d=0;d<f;d++){var
o=bW(a.read32s()),n=bW(a.read32s());i.set(d,[aZ,o,n])}break;case
11:var
g=new
Array(8);for(var
d=0;d<f;d++){for(var
e=0;e<8;e++)g[e]=a.read8u();var
o=bX(aN(g));for(var
e=0;e<8;e++)g[e]=a.read8u();var
n=bX(aN(g));i.set(d,[aZ,o,n])}break}b[0]=(4+k)*4;return dj(l,q,j,h)}function
di(a,b,c){return a.compare(b,c)}function
dG(a,b){return Math.imul(a,b)}function
ab(a,b){b=dG(b,0xcc9e2d51|0);b=b<<15|b>>>32-15;b=dG(b,0x1b873593);a^=b;a=a<<13|a>>>32-13;return(a+(a<<2)|0)+(0xe6546b64|0)|0}function
gC(a,b){a=ab(a,bZ(b));a=ab(a,bY(b));return a}function
dy(a,b){return gC(a,a8(b))}function
dm(a){var
c=bP(a.dims),d=0;switch(a.kind){case
2:case
3:case
12:if(c>cW)c=cW;var
e=0,b=0;for(b=0;b+4<=a.data.length;b+=4){e=a.data[b+0]|a.data[b+1]<<8|a.data[b+2]<<16|a.data[b+3]<<24;d=ab(d,e)}e=0;switch(c&3){case
3:e=a.data[b+2]<<16;case
2:e|=a.data[b+1]<<8;case
1:e|=a.data[b+0];d=ab(d,e)}break;case
4:case
5:if(c>aK)c=aK;var
e=0,b=0;for(b=0;b+2<=a.data.length;b+=2){e=a.data[b+0]|a.data[b+1]<<16;d=ab(d,e)}if((c&1)!==0)d=ab(d,a.data[b]);break;case
6:if(c>64)c=64;for(var
b=0;b<c;b++)d=ab(d,a.data[b]);break;case
8:case
9:if(c>64)c=64;for(var
b=0;b<c;b++)d=ab(d,a.data[b]);break;case
7:if(c>32)c=32;c*=2;for(var
b=0;b<c;b++)d=ab(d,a.data[b]);break;case
10:c*=2;case
0:if(c>64)c=64;for(var
b=0;b<c;b++)d=dy(d,a.data[b]);break;case
11:c*=2;case
1:if(c>32)c=32;for(var
b=0;b<c;b++)d=dy(d,a.data[b]);break}return d}function
gE(a,b){b[0]=4;return a.read32s()}function
gZ(a,b){switch(a.read8u()){case
1:b[0]=4;return a.read32s();case
2:at("input_value: native integer value too large");break;default:at("input_value: ill-formed native integer")}}function
gP(a,b){var
d=new
Array(8);for(var
c=0;c<8;c++)d[c]=a.read8u();b[0]=8;return aN(d)}function
gL(a,b,c){var
e=aO(b);for(var
d=0;d<8;d++)a.write(8,e[d]);c[0]=8;c[1]=8}function
gF(a,b,c){return a.compare(b)}function
gI(a){return a.lo32()^a.hi32()}var
dt={_j:{deserialize:gP,serialize:gL,fixed_length:8,compare:gF,hash:gI},_i:{deserialize:gE,fixed_length:4},_n:{deserialize:gZ,fixed_length:4},_bigarray:{deserialize:function(a,b){return dk(a,b,"_bigarray")},serialize:dn,compare:di,hash:dm},_bigarr02:{deserialize:function(a,b){return dk(a,b,a0)},serialize:dn,compare:di,hash:dm}};function
bS(a){return dt[a.caml_custom]&&dt[a.caml_custom].compare}function
dr(a,b,c,d){var
f=bS(b);if(f){var
e=c>0?f(b,a,d):f(a,b,d);if(d&&Number.isNaN(e))return c;if(Number.isNaN(+e))return+e;if((e|0)!==0)return e|0}return c}function
ds(a){if(typeof
a==="number")return aI;else if(b0(a))return aY;else if(b1(a))return 1252;else if(Array.isArray(a)&&a[0]===a[0]>>>0&&a[0]<=cX){var
b=a[0]|0;return b===aZ?0:b}else if(a
instanceof
String)return cu;else if(typeof
a==="string")return cu;else if(a
instanceof
Number)return aI;else if(a&&a.caml_custom)return bz;else if(a&&a.compare)return 1256;else if(typeof
a==="function")return 1247;else if(typeof
a==="symbol")return 1251;return 1001}function
gQ(a,b){if(a<b)return-1;if(a===b)return 0;return 1}function
he(a,b){return a<b?-1:a>b?1:0}function
gt(a,b){a.t&6&&a6(a);b.t&6&&a6(b);return a.c<b.c?-1:a.c>b.c?1:0}function
gv(a,b,c){var
f=[];for(;;){if(!(c&&a===b)){var
e=ds(a);if(e===cs){a=a[1];continue}var
h=ds(b);if(h===cs){b=b[1];continue}if(e!==h){if(e===aI){if(h===bz)return dr(a,b,-1,c);return-1}if(h===aI){if(e===bz)return dr(b,a,1,c);return 1}return e<h?-1:1}switch(e){case
247:g(bE);break;case
248:var
d=gQ(a[2],b[2])|0;if(d!==0)return d;break;case
249:g(bE);break;case
250:g("equal: got Forward_tag, should not happen");break;case
251:g("equal: abstract value");break;case
252:if(a!==b){var
d=gt(a,b)|0;if(d!==0)return d}break;case
253:g("equal: got Double_tag, should not happen");break;case
254:g("equal: got Double_array_tag, should not happen");break;case
255:g("equal: got Custom_tag, should not happen");break;case
1247:g(bE);break;case
1255:var
j=bS(a);if(j!==bS(b))return a.caml_custom<b.caml_custom?-1:1;if(!j)g("compare: abstract value");var
d=j(a,b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1256:var
d=a.compare(b,c);if(Number.isNaN(d))return c?-1:d;if(d!==(d|0))return-1;if(d!==0)return d|0;break;case
1000:a=+a;b=+b;if(a<b)return-1;if(a>b)return 1;if(a!==b){if(!c)return Number.NaN;if(!Number.isNaN(a))return 1;if(!Number.isNaN(b))return-1}break;case
1001:if(a<b)return-1;if(a>b)return 1;if(a!==b)return c?1:Number.NaN;break;case
1251:if(a!==b)return c?1:Number.NaN;break;case
1252:var
a=aj(a),b=aj(b);if(a!==b){if(a<b)return-1;if(a>b)return 1}break;case
12520:var
a=a.toString(),b=b.toString();if(a!==b){if(a<b)return-1;if(a>b)return 1}break;default:if(gR(e)){g("compare: continuation value");break}if(a.length!==b.length)return a.length<b.length?-1:1;if(a.length>1)f.push(a,b,1);break}}if(f.length===0)return 0;var
i=f.pop();b=f.pop();a=f.pop();if(i+1<a.length)f.push(a,b,i+1);a=a[i];b=b[i]}}function
aP(a,b){return+(gv(a,b,false)!==0)}function
a_(a){if(Array.isArray(a)&&a[0]===a[0]>>>0)return a[0];else if(b0(a))return aY;else if(b1(a))return aY;else if(a
instanceof
Function||typeof
a==="function")return 247;else if(a&&a.caml_custom)return cX;else
return aI}var
dP=undefined;function
gr(a){var
d={},c=-1;if(a)for(var
b=1;b<a.length;b++){var
e=a[b][2];c=Math.max(c,e);d[dB(a[b][1])]=e}d.next_idx=c+1;return d}function
M(a,b,c){if(c){var
d=c;if(dP)a=a4(dP,[d]);else if(z.symbols){if(!z.symidx)z.symidx=gr(z.symbols);var
e=z.symidx[d];if(e>=0)a=e;else{var
a=z.symidx.next_idx++;z.symidx[d]=a}}}z[a+1]=b;if(c)z[c]=b}function
b4(a,b){dH[aj(a)]=b;return 0}function
g5(){g(bw)}function
H(a,b){if(b>>>0>=D(a))g5();return bb(a,b)}function
K(a){a.t&6&&a6(a);return N(a.c)}function
g6(){return 0x7fffffff/4|0}function
b5(a){var
b=1;while(a&&a.joo_tramp){a=a.joo_tramp.apply(null,a.joo_args);b++}return a}function
v(a,b){return{joo_tramp:a,joo_args:b}}function
b6(a){{if(Array.isArray(a))return a;var
b;if(c.RangeError&&a
instanceof
c.RangeError&&a.message&&a.message.match(/maximum call stack/i))b=z.Stack_overflow;else if(c.InternalError&&a
instanceof
c.InternalError&&a.message&&a.message.match(/too much recursion/i))b=z.Stack_overflow;else if(a
instanceof
c.Error&&al(bt))b=[0,al(bt),a];else
b=[0,z.Failure,R(String(a))];if(a
instanceof
c.Error)b.js_error=a;return b}}function
gS(a){switch(a[2]){case-8:case-11:case-12:return 1;default:return 0}}function
gA(a){var
b=f;if(a[0]===0){b+=a[1][1];if(a.length===3&&a[2][0]===0&&gS(a[1]))var
e=a[2],g=1;else
var
g=2,e=a;b+="(";for(var
d=g;d<e.length;d++){if(d>g)b+=cC;var
c=e[d];if(typeof
c==="number")b+=c.toString();else if(c
instanceof
aa)b+=aX+c.toString()+aX;else if(typeof
c==="string")b+=aX+c.toString()+aX;else
b+=cQ}b+=")"}else if(a[0]===t)b+=a[1];return b}function
du(a){if(Array.isArray(a)&&(a[0]===0||a[0]===t)){var
c=al(cU);if(c)a4(c,[a,false]);else{var
d=gA(a),b=al(c$);if(b)a4(b,[0]);console.error(bA+d);if(a.js_error)throw a.js_error}}else
throw a}function
g4(){var
d=c.process;if(d&&d.on)d.on("uncaughtException",function(a,b){du(a);d.exit(2)});else if(c.addEventListener)c.addEventListener("error",function(a){if(a.error)du(a.error)})}g4();function
s(a,b){return(a.l>=0?a.l:a.l=a.length)===1?a(b):as(a,[b])}function
J(a,b,c){return(a.l>=0?a.l:a.l=a.length)===2?a(b,c):as(a,[b,c])}function
bs(a,b,c,d,e,f){return(a.l>=0?a.l:a.l=a.length)===5?a(b,c,d,e,f):as(a,[b,c,d,e,f])}function
gn(a,b,c,d,e,f,g,h){return(a.l>=0?a.l:a.l=a.length)===7?a(b,c,d,e,f,g,h):as(a,[b,c,d,e,f,g,h])}var
hd=0;gB();var
bf=[t,dc,-1],cb=[t,c3,-2],b_=[t,bM,-3],b9=[t,cG,-4],b$=[t,c8,-8],ca=[t,cy,-9],p=[t,cM,-11],cc=[t,c1,-12],gm=[4,0,0,0,[12,45,[4,0,0,0,0]]],bl=[0,[11,'File "',[2,0,[11,'", line ',[4,0,0,0,[11,da,[4,0,0,0,[12,45,[4,0,0,0,[11,": ",[2,0,0]]]]]]]]]],'File "%s", line %d, characters %d-%d: %s'];M(11,cc,c1);M(10,p,cM);M(9,[t,cR,-10],cR);M(8,ca,cy);M(7,b$,c8);M(6,[t,cI,-7],cI);M(5,[t,cZ,-6],cZ);M(4,[t,dd,-5],dd);M(3,b9,cG);M(2,b_,bM);M(1,cb,c3);M(0,bf,dc);function
n(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,n(a[1])];case
1:return[1,n(a[1])];case
2:return[2,n(a[1])];case
3:return[3,n(a[1])];case
4:return[4,n(a[1])];case
5:return[5,n(a[1])];case
6:return[6,n(a[1])];case
7:return[7,n(a[1])];case
8:var
c=a[1];return[8,c,n(a[2])];case
9:var
b=a[1];return[9,b,b,n(a[3])];case
10:return[10,n(a[1])];case
11:return[11,n(a[1])];case
12:return[12,n(a[1])];case
13:return[13,n(a[1])];default:return[14,n(a[1])]}}function
A(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,A(a[1],b)];case
1:return[1,A(a[1],b)];case
2:return[2,A(a[1],b)];case
3:return[3,A(a[1],b)];case
4:return[4,A(a[1],b)];case
5:return[5,A(a[1],b)];case
6:return[6,A(a[1],b)];case
7:return[7,A(a[1],b)];case
8:var
c=a[1];return[8,c,A(a[2],b)];case
9:var
d=a[2],e=a[1];return[9,e,d,A(a[3],b)];case
10:return[10,A(a[1],b)];case
11:return[11,A(a[1],b)];case
12:return[12,A(a[1],b)];case
13:return[13,A(a[1],b)];default:return[14,A(a[1],b)]}}function
m(a,b){if(typeof
a==="number")return b;switch(a[0]){case
0:return[0,m(a[1],b)];case
1:return[1,m(a[1],b)];case
2:var
c=a[1];return[2,c,m(a[2],b)];case
3:var
d=a[1];return[3,d,m(a[2],b)];case
4:var
e=a[3],f=a[2],g=a[1];return[4,g,f,e,m(a[4],b)];case
5:var
h=a[3],i=a[2],j=a[1];return[5,j,i,h,m(a[4],b)];case
6:var
k=a[3],l=a[2],n=a[1];return[6,n,l,k,m(a[4],b)];case
7:var
o=a[3],p=a[2],q=a[1];return[7,q,p,o,m(a[4],b)];case
8:var
r=a[3],s=a[2],t=a[1];return[8,t,s,r,m(a[4],b)];case
9:var
u=a[1];return[9,u,m(a[2],b)];case
10:return[10,m(a[1],b)];case
11:var
v=a[1];return[11,v,m(a[2],b)];case
12:var
w=a[1];return[12,w,m(a[2],b)];case
13:var
x=a[2],y=a[1];return[13,y,x,m(a[3],b)];case
14:var
z=a[2],A=a[1];return[14,A,z,m(a[3],b)];case
15:return[15,m(a[1],b)];case
16:return[16,m(a[1],b)];case
17:var
B=a[1];return[17,B,m(a[2],b)];case
18:var
C=a[1];return[18,C,m(a[2],b)];case
19:return[19,m(a[1],b)];case
20:var
D=a[2],E=a[1];return[20,E,D,m(a[3],b)];case
21:var
F=a[1];return[21,F,m(a[2],b)];case
22:return[22,m(a[1],b)];case
23:var
G=a[1];return[23,G,m(a[2],b)];default:var
H=a[2],I=a[1];return[24,I,H,m(a[3],b)]}}var
dS="true",dT="false";function
aB(a){throw h([0,b9,a],1)}function
aR(a){return 0<=a?a:-a|0}gV(0);dD(1);var
O=dD(2);function
aC(a,b){dE(a,b,0,D(b))}function
cd(a){aC(O,a);dF(O,10);return ac(O)}var
dU=[0,function(a){var
b=gW(0);for(;;){if(!b)return 0;var
d=b[2],e=b[1];try{ac(e)}catch(f){var
c=b6(f);if(c[1]!==cb)throw h(c,0)}b=d}}];function
bg(a){return s(bO(dU),0)}b4(c$,bg);var
aD=(4*g6(0)|0)-1|0,d1="String.sub / Bytes.sub",d2="Bytes.blit",d3="String.blit / Bytes.blit_string";function
am(a,b){var
c=y(a);gz(c,0,a,b);return c}function
ce(a,b,c){a:{if(0<=b&&0<=c&&(V(a)-c|0)>=b){var
d=y(c);ai(a,b,d,0,c);var
e=d;break a}var
e=aB(d1)}return K(e)}function
cf(a,b,c,d,e){if(0<=e&&0<=b&&(V(a)-e|0)>=b&&0<=d&&(V(c)-e|0)>=d){ai(a,b,c,d,e);return}return aB(d2)}function
S(a,b,c,d,e){if(0<=e&&0<=b&&(D(a)-e|0)>=b&&0<=d&&(V(c)-e|0)>=d){a3(a,b,c,d,e);return}return aB(d3)}var
d4="Buffer.add: cannot grow buffer";function
cg(a,b){var
d=a[2],c=[0,a[1][2]];for(;;){if(c[1]>=(d+b|0))break;c[1]=2*c[1]|0}if(aD<c[1]){if((d+b|0)>aD)throw h([0,b_,d4],1);c[1]=aD}var
e=y(c[1]);cf(a[1][1],0,e,0,a[2]);a[1]=[0,e,c[1]]}function
aE(a,b){var
c=D(b),d=a[2],e=a[1],f=d+c|0,g=e[1];if(e[2]<f){cg(a,c);S(b,0,a[1][1],a[2],c)}else
a3(b,0,g,d,c);a[2]=f}var
d5="@]",d6="@}",d7="@?",d8="@\n",d9="@.",d_="@@",d$="@%",ea="%c",eb="%s",ec=cN,ed=cA,ee=df,ef=cH,eg="%f",eh="%B",ei="%{",ej="%}",ek="%(",el="%)",em="%a",en="%t",eo="%?",ep="%r",eq="%_r",er=[0,a,850,23],es=[0,a,837,26],et=[0,a,847,28],eu=[0,a,815,21],ev=[0,a,819,21],ew=[0,a,823,19],ex=[0,a,827,22],ey=[0,a,832,30],ez=[0,a,851,23],eA=[0,a,836,26],eB=[0,a,846,28],eC=[0,a,814,21],eD=[0,a,818,21],eE=[0,a,822,19],eF=[0,a,826,22],eG=[0,a,831,30];function
bi(a){return 5===a[2]?12:-6}function
ch(a){return[0,0,y(a)]}function
ci(a,b){var
c=V(a[2]),d=a[1]+b|0;if(c<d){var
e=c*2|0,g=d<=e?e:d,f=y(g);cf(a[2],0,f,0,c);a[2]=f}}function
au(a,b){ci(a,1);ar(a[2],a[1],b);a[1]=a[1]+1|0}function
w(a,b){var
c=D(b);ci(a,c);S(b,0,a[2],a[1],c);a[1]=a[1]+c|0}function
cj(a){return ce(a[2],0,a[1])}function
ck(a){if(typeof
a==="number")switch(a){case
0:return d5;case
1:return d6;case
2:return d7;case
3:return d8;case
4:return d9;case
5:return d_;default:return d$}switch(a[0]){case
0:return a[1];case
1:return a[1];default:return"@"+K(am(1,a[1]))}}function
bj(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
d=c[1];w(a,ea);c=d;break;case
1:var
e=c[1];w(a,eb);c=e;break;case
2:var
f=c[1];w(a,ec);c=f;break;case
3:var
g=c[1];w(a,ed);c=g;break;case
4:var
h=c[1];w(a,ee);c=h;break;case
5:var
i=c[1];w(a,ef);c=i;break;case
6:var
j=c[1];w(a,eg);c=j;break;case
7:var
k=c[1];w(a,eh);c=k;break;case
8:var
l=c[2],m=c[1];w(a,ei);bj(a,m);w(a,ej);c=l;break;case
9:var
n=c[3],o=c[1];w(a,ek);bj(a,o);w(a,el);c=n;break;case
10:var
p=c[1];w(a,em);c=p;break;case
11:var
q=c[1];w(a,en);c=q;break;case
12:var
r=c[1];w(a,eo);c=r;break;case
13:var
s=c[1];w(a,ep);c=s;break;default:var
t=c[1];w(a,eq);c=t}}}function
q(a){if(typeof
a==="number")return 0;switch(a[0]){case
0:return[0,q(a[1])];case
1:return[1,q(a[1])];case
2:return[2,q(a[1])];case
3:return[3,q(a[1])];case
4:return[4,q(a[1])];case
5:return[5,q(a[1])];case
6:return[6,q(a[1])];case
7:return[7,q(a[1])];case
8:var
b=a[1];return[8,b,q(a[2])];case
9:var
c=a[2],d=a[1];return[9,c,d,q(a[3])];case
10:return[10,q(a[1])];case
11:return[11,q(a[1])];case
12:return[12,q(a[1])];case
13:return[13,q(a[1])];default:return[14,q(a[1])]}}function
x(a){if(typeof
a==="number")return[0,,function(a){},,function(a){}];switch(a[0]){case
0:var
b=x(a[1]),t=b[2];return[0,,function(a){t(0)},,b[4]];case
1:var
c=x(a[1]),u=c[2];return[0,,function(a){u(0)},,c[4]];case
2:var
d=x(a[1]),v=d[2];return[0,,function(a){v(0)},,d[4]];case
3:var
e=x(a[1]),w=e[2];return[0,,function(a){w(0)},,e[4]];case
4:var
f=x(a[1]),y=f[2];return[0,,function(a){y(0)},,f[4]];case
5:var
g=x(a[1]),z=g[2];return[0,,function(a){z(0)},,g[4]];case
6:var
h=x(a[1]),A=h[2];return[0,,function(a){A(0)},,h[4]];case
7:var
i=x(a[1]),B=i[2];return[0,,function(a){B(0)},,i[4]];case
8:var
k=x(a[2]),C=k[2];return[0,,function(a){C(0)},,k[4]];case
9:var
D=a[2],E=a[1],l=x(a[3]),F=l[4],G=l[2],m=x(j(q(E),D)),H=m[4],I=m[2];return[0,,function(a){I(0);G(0)},,function(a){H(0);F(0)}];case
10:var
n=x(a[1]),J=n[2];return[0,,function(a){J(0)},,n[4]];case
11:var
o=x(a[1]),K=o[2];return[0,,function(a){K(0)},,o[4]];case
12:var
p=x(a[1]),L=p[2];return[0,,function(a){L(0)},,p[4]];case
13:var
r=x(a[1]),M=r[4],N=r[2];return[0,,function(a){N(0)},,function(a){M(0)}];default:var
s=x(a[1]),O=s[4],P=s[2];return[0,,function(a){P(0)},,function(a){O(0)}]}}function
j(a,b){a:{b:{c:{d:{e:{f:{g:{if(typeof
a!=="number"){switch(a[0]){case
0:var
d=a[1];if(typeof
b!=="number")switch(b[0]){case
0:return[0,j(d,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
1:var
e=a[1];if(typeof
b!=="number")switch(b[0]){case
1:return[1,j(e,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
2:var
f=a[1];if(typeof
b!=="number")switch(b[0]){case
2:return[2,j(f,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
3:var
g=a[1];if(typeof
b!=="number")switch(b[0]){case
3:return[3,j(g,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
4:var
i=a[1];if(typeof
b!=="number")switch(b[0]){case
4:return[4,j(i,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
5:var
k=a[1];if(typeof
b!=="number")switch(b[0]){case
5:return[5,j(k,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
6:var
l=a[1];if(typeof
b!=="number")switch(b[0]){case
6:return[6,j(l,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
7:var
m=a[1];if(typeof
b!=="number")switch(b[0]){case
7:return[7,j(m,b[1])];case
8:break f;case
9:break g;case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}break;case
8:var
n=a[2],o=a[1];if(typeof
b!=="number")switch(b[0]){case
8:var
r=b[1],s=j(n,b[2]);return[8,j(o,r),s];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw h([0,p,eA],1);case
9:var
t=a[3],u=a[2],v=a[1];if(typeof
b!=="number")switch(b[0]){case
8:break f;case
9:var
w=b[3],y=b[2],z=b[1],c=x(j(q(u),z)),A=c[4];c[2].call(null,0);A(0);return[9,v,y,j(t,w)];case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e}throw h([0,p,eB],1);case
10:var
B=a[1];if(typeof
b!=="number"&&10===b[0])return[10,j(B,b[1])];throw h([0,p,eC],1);case
11:var
C=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:return[11,j(C,b[1])]}throw h([0,p,eD],1);case
12:var
D=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:return[12,j(D,b[1])]}throw h([0,p,eE],1);case
13:var
E=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:return[13,j(E,b[1])]}throw h([0,p,eF],1);default:var
F=a[1];if(typeof
b!=="number")switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:return[14,j(F,b[1])]}throw h([0,p,eG],1)}throw h([0,p,ez],1)}if(typeof
b==="number")return 0;switch(b[0]){case
10:break a;case
11:break b;case
12:break c;case
13:break d;case
14:break e;case
8:break f;case
9:break;default:throw h([0,p,er],1)}}throw h([0,p,et],1)}throw h([0,p,es],1)}throw h([0,p,ey],1)}throw h([0,p,ex],1)}throw h([0,p,ew],1)}throw h([0,p,ev],1)}throw h([0,p,eu],1)}var
r=[t,"CamlinternalFormat.Type_mismatch",dv(0)];function
dR(a){return a?dS:dT}var
dV="\\\\",dW="\\'",dX="\\b",dY="\\t",dZ="\\n",d0="\\r",eI=bv,eJ="%+d",eK="% d",eL=cN,eM="%+i",eN="% i",eO="%x",eP="%#x",eQ="%X",eR="%#X",eS="%o",eT="%#o",eU=dg,eV="%Ld",eW="%+Ld",eX="% Ld",eY=cH,eZ="%+Li",e0="% Li",e1="%Lx",e2="%#Lx",e3="%LX",e4="%#LX",e5="%Lo",e6="%#Lo",e7="%Lu",e8="%ld",e9="%+ld",e_="% ld",e$=cA,fa="%+li",fb="% li",fc="%lx",fd="%#lx",fe="%lX",ff="%#lX",fg="%lo",fh="%#lo",fi="%lu",fj="%nd",fk="%+nd",fl="% nd",fm=df,fn="%+ni",fo="% ni",fp="%nx",fq="%#nx",fr="%nX",fs="%#nX",ft="%no",fu="%#no",fv="%nu",fw=[0,cr],fB="neg_infinity",fC=c7,fD=bC,fF=[0,a,1558,4],fG="Printf: bad conversion %[",fH=[0,a,1626,39],fI=[0,a,1649,31],fJ=[0,a,1650,31],fK="Printf: bad conversion %_",fL=cY,fM=cP,fN=cY,fO=cP;function
aS(a,b){if(typeof
a==="number")return[0,0,b];if(0===a[0])return[0,[0,a[1],a[2]],b];if(typeof
b!=="number"&&2===b[0])return[0,[1,a[1]],b[1]];throw h(r,1)}function
aF(a,b,c){var
d=aS(a,c);if(typeof
b!=="number")return[0,d[1],[0,b[1]],d[2]];if(!b)return[0,d[1],0,d[2]];var
e=d[2];if(typeof
e!=="number"&&2===e[0])return[0,d[1],1,e[1]];throw h(r,1)}function
l(a,b){if(typeof
a==="number")return[0,0,b];switch(a[0]){case
0:if(typeof
b!=="number"&&0===b[0]){var
w=l(a[1],b[1]);return[0,[0,w[1]],w[2]]}break;case
1:if(typeof
b!=="number"&&0===b[0]){var
x=l(a[1],b[1]);return[0,[1,x[1]],x[2]]}break;case
2:var
ag=a[2],y=aS(a[1],b),e=y[2],ah=y[1];if(typeof
e!=="number"&&1===e[0]){var
z=l(ag,e[1]);return[0,[2,ah,z[1]],z[2]]}throw h(r,1);case
3:var
ai=a[2],A=aS(a[1],b),f=A[2],aj=A[1];if(typeof
f!=="number"&&1===f[0]){var
B=l(ai,f[1]);return[0,[3,aj,B[1]],B[2]]}throw h(r,1);case
4:var
ak=a[4],al=a[1],g=aF(a[2],a[3],b),i=g[3],am=g[1];if(typeof
i!=="number"&&2===i[0]){var
an=g[2],D=l(ak,i[1]);return[0,[4,al,am,an,D[1]],D[2]]}throw h(r,1);case
5:var
ao=a[4],ap=a[1],j=aF(a[2],a[3],b),k=j[3],aq=j[1];if(typeof
k!=="number"&&3===k[0]){var
ar=j[2],F=l(ao,k[1]);return[0,[5,ap,aq,ar,F[1]],F[2]]}throw h(r,1);case
6:var
as=a[4],at=a[1],m=aF(a[2],a[3],b),o=m[3],au=m[1];if(typeof
o!=="number"&&4===o[0]){var
av=m[2],G=l(as,o[1]);return[0,[6,at,au,av,G[1]],G[2]]}throw h(r,1);case
7:var
aw=a[4],ax=a[1],p=aF(a[2],a[3],b),q=p[3],ay=p[1];if(typeof
q!=="number"&&5===q[0]){var
az=p[2],H=l(aw,q[1]);return[0,[7,ax,ay,az,H[1]],H[2]]}throw h(r,1);case
8:var
aA=a[4],aB=a[1],s=aF(a[2],a[3],b),t=s[3],aC=s[1];if(typeof
t!=="number"&&6===t[0]){var
aD=s[2],I=l(aA,t[1]);return[0,[8,aB,aC,aD,I[1]],I[2]]}throw h(r,1);case
9:var
aE=a[2],J=aS(a[1],b),u=J[2],aG=J[1];if(typeof
u!=="number"&&7===u[0]){var
K=l(aE,u[1]);return[0,[9,aG,K[1]],K[2]]}throw h(r,1);case
10:var
L=l(a[1],b);return[0,[10,L[1]],L[2]];case
11:var
aH=a[1],M=l(a[2],b);return[0,[11,aH,M[1]],M[2]];case
12:var
aI=a[1],N=l(a[2],b);return[0,[12,aI,N[1]],N[2]];case
13:if(typeof
b!=="number"&&8===b[0]){var
O=b[1],aJ=b[2],aK=a[3],aL=a[1];if(aP([0,a[2]],[0,O]))throw h(r,1);var
P=l(aK,aJ);return[0,[13,aL,O,P[1]],P[2]]}break;case
14:if(typeof
b!=="number"&&9===b[0]){var
Q=b[1],aM=b[3],aN=a[3],aO=a[2],aQ=a[1],aR=[0,n(Q)];if(aP([0,n(aO)],aR))throw h(r,1);var
R=l(aN,n(aM));return[0,[14,aQ,Q,R[1]],R[2]]}break;case
15:if(typeof
b!=="number"&&10===b[0]){var
S=l(a[1],b[1]);return[0,[15,S[1]],S[2]]}break;case
16:if(typeof
b!=="number"&&11===b[0]){var
T=l(a[1],b[1]);return[0,[16,T[1]],T[2]]}break;case
17:var
aT=a[1],U=l(a[2],b);return[0,[17,aT,U[1]],U[2]];case
18:var
V=a[2],v=a[1];if(0===v[0]){var
Z=v[1],aX=Z[2],_=l(Z[1],b),aY=_[1],$=l(V,_[2]);return[0,[18,[0,[0,aY,aX]],$[1]],$[2]]}var
aa=v[1],aZ=aa[2],ab=l(aa[1],b),a0=ab[1],ac=l(V,ab[2]);return[0,[18,[1,[0,a0,aZ]],ac[1]],ac[2]];case
19:if(typeof
b!=="number"&&13===b[0]){var
W=l(a[1],b[1]);return[0,[19,W[1]],W[2]]}break;case
20:if(typeof
b!=="number"&&1===b[0]){var
aU=a[2],aV=a[1],X=l(a[3],b[1]);return[0,[20,aV,aU,X[1]],X[2]]}break;case
21:if(typeof
b!=="number"&&2===b[0]){var
aW=a[1],Y=l(a[2],b[1]);return[0,[21,aW,Y[1]],Y[2]]}break;case
23:var
d=a[2],c=a[1];if(typeof
c!=="number")switch(c[0]){case
0:return E(c,d,b);case
1:return E(c,d,b);case
2:return E(c,d,b);case
3:return E(c,d,b);case
4:return E(c,d,b);case
5:return E(c,d,b);case
6:return E(c,d,b);case
7:return E(c,d,b);case
8:return E([8,c[1],c[2]],d,b);case
9:var
a1=c[1],ae=C(c[2],d,b),af=ae[2];return[0,[23,[9,a1,ae[1]],af[1]],af[2]];case
10:return E(c,d,b);default:return E(c,d,b)}switch(c){case
0:return E(c,d,b);case
1:return E(c,d,b);case
2:if(typeof
b!=="number"&&14===b[0]){var
ad=l(d,b[1]);return[0,[23,2,ad[1]],ad[2]]}throw h(r,1);default:return E(c,d,b)}}throw h(r,1)}function
E(a,b,c){var
d=l(b,c);return[0,[23,a,d[1]],d[2]]}function
C(a,b,c){if(typeof
a==="number")return[0,0,l(b,c)];switch(a[0]){case
0:if(typeof
c!=="number"&&0===c[0]){var
f=C(a[1],b,c[1]);return[0,[0,f[1]],f[2]]}break;case
1:if(typeof
c!=="number"&&1===c[0]){var
g=C(a[1],b,c[1]);return[0,[1,g[1]],g[2]]}break;case
2:if(typeof
c!=="number"&&2===c[0]){var
i=C(a[1],b,c[1]);return[0,[2,i[1]],i[2]]}break;case
3:if(typeof
c!=="number"&&3===c[0]){var
k=C(a[1],b,c[1]);return[0,[3,k[1]],k[2]]}break;case
4:if(typeof
c!=="number"&&4===c[0]){var
m=C(a[1],b,c[1]);return[0,[4,m[1]],m[2]]}break;case
5:if(typeof
c!=="number"&&5===c[0]){var
o=C(a[1],b,c[1]);return[0,[5,o[1]],o[2]]}break;case
6:if(typeof
c!=="number"&&6===c[0]){var
p=C(a[1],b,c[1]);return[0,[6,p[1]],p[2]]}break;case
7:if(typeof
c!=="number"&&7===c[0]){var
s=C(a[1],b,c[1]);return[0,[7,s[1]],s[2]]}break;case
8:if(typeof
c!=="number"&&8===c[0]){var
t=c[1],D=c[2],E=a[2];if(aP([0,a[1]],[0,t]))throw h(r,1);var
u=C(E,b,D);return[0,[8,t,u[1]],u[2]]}break;case
9:if(typeof
c!=="number"&&9===c[0]){var
d=c[2],e=c[1],F=c[3],G=a[3],H=a[2],I=a[1],J=[0,n(e)];if(aP([0,n(I)],J))throw h(r,1);var
K=[0,n(d)];if(aP([0,n(H)],K))throw h(r,1);var
v=x(j(q(e),d)),L=v[4];v[2].call(null,0);L(0);var
w=C(n(G),b,F),M=w[2];return[0,[9,e,d,q(w[1])],M]}break;case
10:if(typeof
c!=="number"&&10===c[0]){var
y=C(a[1],b,c[1]);return[0,[10,y[1]],y[2]]}break;case
11:if(typeof
c!=="number"&&11===c[0]){var
z=C(a[1],b,c[1]);return[0,[11,z[1]],z[2]]}break;case
13:if(typeof
c!=="number"&&13===c[0]){var
A=C(a[1],b,c[1]);return[0,[13,A[1]],A[2]]}break;case
14:if(typeof
c!=="number"&&14===c[0]){var
B=C(a[1],b,c[1]);return[0,[14,B[1]],B[2]]}break}throw h(r,1)}function
F(a,b,c){var
d=D(c),g=0<=b?a:0,f=aR(b);if(f<=d)return c;var
h=2===g?48:32,e=am(f,h);switch(g){case
0:S(c,0,e,0,d);break;case
1:S(c,0,e,f-d|0,d);break;default:a:if(0<d){if(43!==H(c,0)&&45!==H(c,0)&&32!==H(c,0))break a;ar(e,0,H(c,0));S(c,1,e,(f-d|0)+1|0,d-1|0);break}a:if(1<d&&48===H(c,0)){if(cF!==H(c,1)&&88!==H(c,1))break a;ar(e,1,H(c,1));S(c,2,e,(f-d|0)+2|0,d-2|0);break}S(c,0,e,f-d|0,d)}return K(e)}function
av(a,b){var
d=aR(a),c=D(b),e=H(b,0);a:{b:{if(58>e){if(32!==e){if(43>e)break a;switch(e-43|0){case
5:c:if(c<(d+2|0)&&1<c){if(cF!==H(b,1)&&88!==H(b,1))break c;var
g=am(d+2|0,48);ar(g,1,H(b,1));S(b,2,g,(d-c|0)+4|0,c-2|0);return K(g)}break b;case
0:case
2:break;case
1:case
3:case
4:break a;default:break b}}if(c>=(d+1|0))break a;var
f=am(d+1|0,48);ar(f,0,e);S(b,1,f,(d-c|0)+2|0,c-1|0);return K(f)}if(71<=e){if(5<e+cT>>>0)break a}else if(65>e)break a}if(c<d){var
h=am(d,48);S(b,0,h,d-c|0,c);return K(h)}}return b}function
eH(a){var
e=aq(a),b=[0,0],k=V(e)-1|0,r=0;if(k>=0){var
h=r;for(;;){var
f=bR(e,h);a:{b:{c:{if(32<=f){var
i=f-34|0;if(58<i>>>0){if(93<=i)break c}else if(56<i-1>>>0)break b;var
j=1;break a}if(11<=f){if(13===f)break b}else if(8<=f)break b}var
j=4;break a}var
j=2}b[1]=b[1]+j|0;var
u=h+1|0;if(k===h)break;h=u}}if(b[1]===V(e))var
m=e;else{var
c=y(b[1]);b[1]=0;var
l=V(e)-1|0,s=0;if(l>=0){var
g=s;for(;;){var
d=bR(e,g);a:{b:{c:{if(35<=d){if(92!==d){if(bF<=d)break c;break b}}else{if(32>d){if(14<=d)break c;switch(d){case
8:o(c,b[1],92);b[1]++;o(c,b[1],98);break a;case
9:o(c,b[1],92);b[1]++;o(c,b[1],116);break a;case
10:o(c,b[1],92);b[1]++;o(c,b[1],110);break a;case
13:o(c,b[1],92);b[1]++;o(c,b[1],114);break a;default:break c}}if(34>d)break b}o(c,b[1],92);b[1]++;o(c,b[1],d);break a}o(c,b[1],92);b[1]++;o(c,b[1],48+(d/cV|0)|0);b[1]++;o(c,b[1],48+((d/10|0)%10|0)|0);b[1]++;o(c,b[1],48+(d%10|0)|0);break a}o(c,b[1],d)}b[1]++;var
t=g+1|0;if(l===g)break;g=t}}var
m=c}var
q=K(m),n=D(q),p=am(n+2|0,34);a3(q,0,p,1,n);return K(p)}function
cl(a,b){var
g=aR(b),e=fw[1];switch(a[2]){case
0:var
c=102;break;case
1:var
c=101;break;case
2:var
c=69;break;case
3:var
c=cr;break;case
4:var
c=71;break;case
5:var
c=e;break;case
6:var
c=104;break;case
7:var
c=72;break;default:var
c=70}var
d=ch(16);au(d,37);switch(a[1]){case
0:break;case
1:au(d,43);break;default:au(d,32)}if(8<=a[2])au(d,35);au(d,46);w(d,f+g);au(d,c);return cj(d)}function
aT(a,b){if(13>a)return b;var
h=[0,0],i=D(b)-1|0,n=0;if(i>=0){var
d=n;for(;;){if(9>=bb(b,d)+cx>>>0)h[1]++;var
q=d+1|0;if(i===d)break;d=q}}var
j=h[1],k=y(D(b)+((j-1|0)/3|0)|0),l=[0,0];function
e(a){ar(k,l[1],a);l[1]++}var
f=[0,((j-1|0)%3|0)+1|0],m=D(b)-1|0,o=0;if(m>=0){var
c=o;for(;;){var
g=bb(b,c);if(9<g+cx>>>0)e(g);else{if(0===f[1]){e(95);f[1]=3}f[1]--;e(g)}var
p=c+1|0;if(m===c)break;c=p}}return K(k)}function
fx(a,b){switch(a){case
1:var
c=eJ;break;case
2:var
c=eK;break;case
4:var
c=eM;break;case
5:var
c=eN;break;case
6:var
c=eO;break;case
7:var
c=eP;break;case
8:var
c=eQ;break;case
9:var
c=eR;break;case
10:var
c=eS;break;case
11:var
c=eT;break;case
0:case
13:var
c=eI;break;case
3:case
14:var
c=eL;break;default:var
c=eU}return aT(a,a7(c,b))}function
fy(a,b){switch(a){case
1:var
c=e9;break;case
2:var
c=e_;break;case
4:var
c=fa;break;case
5:var
c=fb;break;case
6:var
c=fc;break;case
7:var
c=fd;break;case
8:var
c=fe;break;case
9:var
c=ff;break;case
10:var
c=fg;break;case
11:var
c=fh;break;case
0:case
13:var
c=e8;break;case
3:case
14:var
c=e$;break;default:var
c=fi}return aT(a,a7(c,b))}function
fz(a,b){switch(a){case
1:var
c=fk;break;case
2:var
c=fl;break;case
4:var
c=fn;break;case
5:var
c=fo;break;case
6:var
c=fp;break;case
7:var
c=fq;break;case
8:var
c=fr;break;case
9:var
c=fs;break;case
10:var
c=ft;break;case
11:var
c=fu;break;case
0:case
13:var
c=fj;break;case
3:case
14:var
c=fm;break;default:var
c=fv}return aT(a,a7(c,b))}function
fA(a,b){switch(a){case
1:var
c=eW;break;case
2:var
c=eX;break;case
4:var
c=eZ;break;case
5:var
c=e0;break;case
6:var
c=e1;break;case
7:var
c=e2;break;case
8:var
c=e3;break;case
9:var
c=e4;break;case
10:var
c=e5;break;case
11:var
c=e6;break;case
0:case
13:var
c=eV;break;case
3:case
14:var
c=eY;break;default:var
c=e7}return aT(a,gH(c,b))}function
W(d,b,c){function
j(a){switch(d[1]){case
0:var
e=45;break;case
1:var
e=43;break;default:var
e=32}return gD(c,b,e)}function
q(a){var
b=gu(c);return 3===b?c<0.?fB:fC:4<=b?fD:a}switch(d[2]){case
5:var
f=bU(cl(d,b),c),e=0,u=D(f);for(;;){if(e===u)var
p=0;else{var
k=H(f,e)-46|0;a:{if(23<k>>>0){if(55===k)break a}else if(21<k-1>>>0)break a;e=e+1|0;continue}var
p=1}var
v=p?f:f+ao;return q(v)}case
6:return j(0);case
7:var
i=aq(j(0)),g=V(i);if(0===g)var
n=i;else{var
l=y(g),m=g-1|0,r=0;if(m>=0){var
a=r;for(;;){var
h=bR(i,a),s=25<h+cT>>>0?h:h-32|0;o(l,a,s);var
t=a+1|0;if(m===a)break;a=t}}var
n=l}return K(n);case
8:return q(j(0));default:return bU(cl(d,b),c)}}function
aG(a,b,c,d){var
f=b,e=c,g=d;for(;;){if(typeof
g==="number")return s(f,e);switch(g[0]){case
0:var
O=g[1];return function(a){return i(f,[5,e,a],O)};case
1:var
P=g[1];return function(a){a:{b:{if(40<=a){if(92===a){var
b=dV;break a}if(bF>a)break b}else{if(32<=a){if(39>a)break b;var
b=dW;break a}if(14>a)switch(a){case
8:var
b=dX;break a;case
9:var
b=dY;break a;case
10:var
b=dZ;break a;case
13:var
b=d0;break a}}var
c=y(4);o(c,0,92);o(c,1,48+(a/cV|0)|0);o(c,2,48+((a/10|0)%10|0)|0);o(c,3,48+(a%10|0)|0);var
b=K(c);break a}var
d=y(1);o(d,0,a);var
b=K(d)}var
g=D(b),h=am(g+2|0,39);a3(b,0,h,1,g);return i(f,[4,e,K(h)],P)};case
2:return bk(f,e,g[2],g[1],function(a){return a});case
3:return bk(f,e,g[2],g[1],eH);case
4:return aU(f,e,g[4],g[2],g[3],fx,g[1]);case
5:return aU(f,e,g[4],g[2],g[3],fy,g[1]);case
6:return aU(f,e,g[4],g[2],g[3],fz,g[1]);case
7:return aU(f,e,g[4],g[2],g[3],fA,g[1]);case
8:var
u=g[4],w=g[3],x=g[2],t=g[1];if(typeof
x==="number"){if(typeof
w==="number")return w?function(a,b){return i(f,[4,e,W(t,a,b)],u)}:function(a){return i(f,[4,e,W(t,bi(t),a)],u)};var
$=w[1];return function(a){return i(f,[4,e,W(t,$,a)],u)}}if(0===x[0]){var
B=x[2],C=x[1];if(typeof
w==="number")return w?function(a,b){return i(f,[4,e,F(C,B,W(t,a,b))],u)}:function(a){return i(f,[4,e,F(C,B,W(t,bi(t),a))],u)};var
aa=w[1];return function(a){return i(f,[4,e,F(C,B,W(t,aa,a))],u)}}var
E=x[1];if(typeof
w==="number")return w?function(a,b,c){return i(f,[4,e,F(E,a,W(t,b,c))],u)}:function(a,b){return i(f,[4,e,F(E,a,W(t,bi(t),b))],u)};var
ab=w[1];return function(a,b){return i(f,[4,e,F(E,a,W(t,ab,b))],u)};case
9:return bk(f,e,g[2],g[1],dR);case
10:e=[7,e];g=g[1];break;case
11:e=[2,e,g[1]];g=g[2];break;case
12:e=[3,e,g[1]];g=g[2];break;case
13:var
Q=g[3],R=g[2],G=ch(16);bj(G,R);var
N=cj(G);return function(a){return i(f,[4,e,N],Q)};case
14:var
S=g[3],T=g[2];return function(a){var
c=a[1],b=l(c,n(q(T)));if(typeof
b[2]==="number")return i(f,e,m(b[1],S));throw h(r,1)};case
15:var
U=g[1];return function(c,b){return i(f,[6,e,function(a){return J(c,a,b)}],U)};case
16:var
V=g[1];return function(a){return i(f,[6,e,a],V)};case
17:e=[0,e,g[1]];g=g[2];break;case
18:var
A=g[1];if(0===A[0]){let
b=e,c=f,d=g[2];f=function(a){return i(c,[1,b,[0,a]],d)};e=0;g=A[1][1]}else{let
b=e,c=f,d=g[2];f=function(a){return i(c,[1,b,[1,a]],d)};e=0;g=A[1][1]}break;case
19:throw h([0,p,fF],1);case
20:var
X=g[3],Y=[8,e,fG];return function(a){return i(f,Y,X)};case
21:var
Z=g[2];return function(a){return i(f,[4,e,a7(dg,a)],Z)};case
22:var
_=g[1];return function(a){return i(f,[5,e,a],_)};case
23:var
j=g[2],z=g[1];if(typeof
z==="number")switch(z){case
0:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
1:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
2:throw h([0,p,fH],1);default:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j])}switch(z[0]){case
0:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
1:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
2:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
3:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
4:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
5:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
6:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
7:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
8:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);case
9:var
M=z[2];return a<50?br(a+1|0,f,e,M,j):v(br,[0,f,e,M,j]);case
10:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j]);default:return a<50?k(a+1|0,f,e,j):v(k,[0,f,e,j])}default:var
H=g[3],I=g[1],L=s(g[2],0);return a<50?bq(a+1|0,f,e,H,I,L):v(bq,[0,f,e,H,I,L])}}}function
i(a,b,c){return b5(aG(0,a,b,c))}function
br(a,f,c,d,e){if(typeof
d==="number")return a<50?k(a+1|0,f,c,e):v(k,[0,f,c,e]);switch(d[0]){case
0:var
b=d[1];return function(a){return I(f,c,b,e)};case
1:var
g=d[1];return function(a){return I(f,c,g,e)};case
2:var
i=d[1];return function(a){return I(f,c,i,e)};case
3:var
l=d[1];return function(a){return I(f,c,l,e)};case
4:var
m=d[1];return function(a){return I(f,c,m,e)};case
5:var
n=d[1];return function(a){return I(f,c,n,e)};case
6:var
o=d[1];return function(a){return I(f,c,o,e)};case
7:var
r=d[1];return function(a){return I(f,c,r,e)};case
8:var
s=d[2];return function(a){return I(f,c,s,e)};case
9:var
t=d[3],u=d[2],w=j(q(d[1]),u);return function(a){return I(f,c,A(w,t),e)};case
10:var
x=d[1];return function(a,b){return I(f,c,x,e)};case
11:var
y=d[1];return function(a){return I(f,c,y,e)};case
12:var
z=d[1];return function(a){return I(f,c,z,e)};case
13:throw h([0,p,fI],1);default:throw h([0,p,fJ],1)}}function
I(a,b,c,d){return b5(br(0,a,b,c,d))}function
k(a,b,c,d){var
e=[8,c,fK];return a<50?aG(a+1|0,b,e,d):v(aG,[0,b,e,d])}function
bk(g,f,c,d,e){if(typeof
d==="number")return function(a){return i(g,[4,f,s(e,a)],c)};if(0===d[0]){var
b=d[2],h=d[1];return function(a){return i(g,[4,f,F(h,b,s(e,a))],c)}}var
j=d[1];return function(a,b){return i(g,[4,f,F(j,a,s(e,b))],c)}}function
aU(k,j,h,d,e,f,g){if(typeof
d==="number"){if(typeof
e==="number")return e?function(a,b){return i(k,[4,j,av(a,J(f,g,b))],h)}:function(a){return i(k,[4,j,J(f,g,a)],h)};var
b=e[1];return function(a){return i(k,[4,j,av(b,J(f,g,a))],h)}}if(0===d[0]){var
c=d[2],l=d[1];if(typeof
e==="number")return e?function(a,b){return i(k,[4,j,F(l,c,av(a,J(f,g,b)))],h)}:function(a){return i(k,[4,j,F(l,c,J(f,g,a))],h)};var
n=e[1];return function(a){return i(k,[4,j,F(l,c,av(n,J(f,g,a)))],h)}}var
m=d[1];if(typeof
e==="number")return e?function(a,b,c){return i(k,[4,j,F(m,a,av(b,J(f,g,c)))],h)}:function(a,b){return i(k,[4,j,F(m,a,J(f,g,b))],h)};var
o=e[1];return function(a,b){return i(k,[4,j,F(m,a,av(o,J(f,g,b)))],h)}}function
bq(a,b,c,d,e,f){if(e){var
h=e[1];return function(a){return fE(b,c,d,h,s(f,a))}}var
g=[4,c,f];return a<50?aG(a+1|0,b,g,d):v(aG,[0,b,g,d])}function
fE(a,b,c,d,e){return b5(bq(0,a,b,c,d,e))}function
X(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
f=c[1],g=ck(c[2]);X(a,f);return aC(a,g);case
1:var
d=c[2],e=c[1];if(0===d[0]){var
h=d[1];X(a,e);aC(a,fL);c=h}else{var
i=d[1];X(a,e);aC(a,fM);c=i}break;case
6:var
l=c[2];X(a,c[1]);return s(l,a);case
7:X(a,c[1]);ac(a);return;case
8:var
m=c[2];X(a,c[1]);return aB(m);case
2:case
4:var
j=c[2];X(a,c[1]);return aC(a,j);default:var
k=c[2];X(a,c[1]);dF(a,k);return}}}function
af(a,b){var
c=b;for(;;){if(typeof
c==="number")return;switch(c[0]){case
0:var
j=c[1],k=ck(c[2]);af(a,j);return aE(a,k);case
1:var
e=c[2],g=c[1];if(0===e[0]){var
l=e[1];af(a,g);aE(a,fN);c=l}else{var
m=e[1];af(a,g);aE(a,fO);c=m}break;case
6:var
p=c[2];af(a,c[1]);return aE(a,s(p,0));case
7:c=c[1];break;case
8:var
q=c[2];af(a,c[1]);return aB(q);case
2:case
4:var
n=c[2];af(a,c[1]);return aE(a,n);default:var
h=c[2];af(a,c[1]);var
d=a[2],f=a[1],i=f[1];if(f[2]<=d){cg(a,1);ar(a[1][1],a[2],h)}else
o(i,d,h);a[2]=d+1|0;return}}}function
aV(c,b){return i(function(a){X(c,a);return 0},0,b[1])}function
L(a){return i(function(a){var
e=64,c=aD<64?aD:e,d=y(c),b=[0,[0,d,c],0,d];af(b,a);return ce(b[1][1],0,b[2])},0,a[1])}var
bh=[0,0],fP=[0,[3,0,0],"%S"],fQ=cQ,fR=[0,[4,0,0,0,0],bv],fS=f,fT=[0,[11,cC,[2,0,[2,0,0]]],", %s%s"],fU=[0,[12,40,[2,0,[2,0,[12,41,0]]]],"(%s%s)"],fV=f,fW=f,fX=[0,[12,40,[2,0,[12,41,0]]],"(%s)"],fY="Out of memory",fZ="Stack overflow",f0="Pattern matching failed",f1="Assertion failed",f2="Undefined recursive module",f3="Raised at",f4="Re-raised at",f5="Raised by primitive operation at",f6="Called from",f7=[0,[12,32,[4,0,0,0,0]]," %d"],f8=" (inlined)",f9=[0,[2,0,[12,32,[2,0,[11,' in file "',[2,0,[12,34,[2,0,[11,", line",[2,0,[11,da,gm]]]]]]]]]],'%s %s in file "%s"%s, line%s, characters %d-%d'],f_=f,f$=[0,[11,"s ",[4,0,0,0,[12,45,[4,0,0,0,0]]]],"s %d-%d"],ga=[0,[2,0,[11," unknown location",0]],"%s unknown location"],gb=[0,[2,0,[12,10,0]],"%s\n"];function
bm(a,b){var
c=a[1+b];if(!(1-(typeof
c==="number"?1:0)))return s(L(fR),c);if(a_(c)===aY)return s(L(fP),c);if(a_(c)!==253)return fQ;var
e=bU("%.12g",c),d=0,g=D(e);for(;;){if(g<=d)return e+ao;var
f=H(e,d);a:{if(48<=f){if(58>f)break a}else if(45===f)break a;return e}d=d+1|0}}function
cm(a,b){if(a.length-1<=b)return fS;var
c=cm(a,b+1|0),d=bm(a,b);return J(L(fT),d,c)}function
bn(a){a:{b:{var
b=bO(bh);for(;;){if(!b)break;c:{var
u=b[2],v=b[1];try{var
j=s(v,a)}catch(f){break c}if(j)break b}b=u}var
h=0;break a}var
h=[0,j[1]]}if(h)return h[1];if(a===bf)return fY;if(a===ca)return fZ;if(a[1]===b$){var
e=a[2],m=e[3],x=e[2],y=e[1];return bs(L(bl),y,x,m,m+5|0,f0)}if(a[1]===p){var
f=a[2],n=f[3],z=f[2],A=f[1];return bs(L(bl),A,z,n,n+6|0,f1)}if(a[1]===cc){var
g=a[2],o=g[3],B=g[2],C=g[1];return bs(L(bl),C,B,o,o+6|0,f2)}if(0===a_(a)){var
i=a.length-1,w=a[1][1];if(2<i>>>0)var
q=cm(a,2),r=bm(a,1),c=J(L(fU),r,q);else
switch(i){case
0:var
c=fV;break;case
1:var
c=fW;break;default:var
t=bm(a,1),c=s(L(fX),t)}var
d=[0,w,[0,c]]}else
var
d=[0,a[1],0];var
k=d[2],l=d[1];return k?l+k[1]:l}function
bo(a,b){var
f=gw(b),i=f.length-2|0,u=0;if(i>=0){var
d=u;for(;;){var
c=dq(f,d)[1+d];let
b=d;var
g=function(a){return a?0===b?f3:f4:0===b?f5:f6};if(0===c[0]){if(c[3]===c[6])var
j=c[3],h=s(L(f7),j);else
var
q=c[6],r=c[3],h=J(L(f$),r,q);var
k=c[7],l=c[4],m=c[8]?f8:f_,n=c[2],o=c[9],p=g(c[1]),e=[0,gn(L(f9),p,o,n,m,h,l,k)]}else if(c[1])var
e=0;else
var
t=g(0),e=[0,s(L(ga),t)];if(e){var
v=e[1];s(aV(a,gb),v)}var
w=d+1|0;if(i===d)break;d=w}}}function
cn(a){for(;;){var
b=bO(bh),c=1-go(bh,b,[0,a,b]);if(!c)return c}}var
gc=[0,f,"(Cannot print locations:\n bytecode executable program file not found)","(Cannot print locations:\n bytecode executable program file appears to be corrupt)","(Cannot print locations:\n bytecode executable program file has wrong magic number)","(Cannot print locations:\n bytecode executable program file cannot be opened;\n -- too many open files. Try running with OCAMLRUNPARAM=b=2)"].slice(),gd=[0,[11,bA,[2,0,[12,10,0]]],ct],ge=[0],gf="Fatal error: out of memory in uncaught exception handler",gg=[0,[11,bA,[2,0,[12,10,0]]],ct],gh=[0,[11,"Fatal error in uncaught exception handler: exception ",[2,0,[12,10,0]]],"Fatal error in uncaught exception handler: exception %s\n"];b4(cU,function(a,b){try{try{var
g=b?ge:dw(0);try{bg(0)}catch(f){}try{var
f=bn(a);s(aV(O,gd),f);bo(O,g);var
c=gU(0);if(c<0){var
d=aR(c);cd(dq(gc,d)[1+d])}var
n=ac(O),i=n}catch(f){var
k=b6(f),l=bn(a);s(aV(O,gg),l);bo(O,g);var
m=bn(k);s(aV(O,gh),m);bo(O,dw(0));var
i=ac(O)}var
j=i}catch(f){var
e=b6(f);if(e!==bf)throw h(e,0);var
j=cd(gf)}return j}catch(f){return 0}});var
co=[t,"Jsoo_runtime.Error.Exn",dv(0)],bp=[0,co,[0]],gk="Pass",gl="Fail",gi=a_(bp)===t?bp:bp[1];b4(bt,gi);(function(a){throw a});var
ag=c;ag.String;ag.RegExp;ag.Object;ag.Date;ag.Math;ag.Error;ag.JSON;var
gj=ag.Array;cn(function(a){return a[1]===co?[0,R(a[2].toString())]:0});cn(function(a){return a
instanceof
gj?0:[0,R(a.toString())]});function
aW(a,b){return a===b?gk:gl}a:{if(R(typeof
aW)==="function"&&0<aW.length){var
cp=dA(aW);break a}var
cp=aW}g9.grade=cp;bg(0);return}(globalThis));
