#!/bin/bash

samples="$(ls ./sample/*.ic)"
for target in ${samples};
do
  echo ""
	echo "testing file: ${target}"
	./run ${target}
done

proofs="$(ls ./proofs/*.ic)"
for target in ${proofs};
do
  echo ""
	echo "testing file: ${target}"
	./run ${target}
done
